# **Pandas :**

- used for working with database
- analyzing,cleaning,explaining and manupalating data
- pandas -->Panel data
         -->Python
- Allow us to analyze big data and make conclusion based on statistical theories. pandas can clean messy database and make   them readable and relevent which is  very important in data science

**> Pandas Series :**

- series is like a column in table. it is 1-D array holding data of any type.

In [2]:
import pandas as pd
a=[1,7,2]
var=pd.Series(a)
print(var)
print(type(var))

0    1
1    7
2    2
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
print(var[1])

7

change the name of index

In [4]:
import pandas as pd
a=[1,7,2]
var=pd.Series(a,index=['x','y','z'])
print(var)
print(type(var))

x    1
y    7
z    2
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
print(var['y'])

7

give input as tuple

In [18]:
import pandas as pd
a=(1.4,2,3,4)
var=pd.Series(a)
print(var)
print(type(var))

0    1.4
1    2.0
2    3.0
3    4.0
dtype: float64
<class 'pandas.core.series.Series'>

In [25]:
import pandas as pd
s_name=['ram','shyam','radha','geeta','seeta']
marks=[50,60,70,80,90]
var=pd.Series(marks,index=s_name,name='Student Result')
print(var)

ram      50
shyam    60
radha    70
geeta    80
seeta    90
Name: Student Result, dtype: int64

In [26]:
import pandas as pd
calories={'day1':400,'day2':380,'day3':430,'day4':390}
var=pd.Series(calories)
print(var)

day1    400
day2    380
day3    430
day4    390
dtype: int64

In [27]:
import pandas as pd
calories={'day1':400,'day2':380,'day3':430,'day4':390}
var=pd.Series(calories,index=['day1','day2'])
print(var)

day1    400
day2    380
dtype: int64

In [28]:
import pandas as pd
calories={'day1':400,'day2':380,'day3':430,'day4':390}
var=pd.Series(calories,name='Calories Burn per day')
print(var)

day1    400
day2    380
day3    430
day4    390
Name: Calories Burn per day, dtype: int64

**> Series Attributes :**

In [16]:
var.size

4

In [19]:
var.dtype

dtype('float64')

In [29]:
var.name

'Calories Burn per day'

In [30]:
var.index

Index(['day1', 'day2', 'day3', 'day4'], dtype='object')

In [32]:
var.values
# list as output

array([400, 380, 430, 390], dtype=int64)

In [33]:
print(var.values)
print(type(var.values))

# array as output

[400 380 430 390]
<class 'numpy.ndarray'>

In [34]:
var.is_unique

# if all values are different then True o.w. false

True

In [36]:
print(pd.Series([55,22,33,44,55]).is_unique)

False

- To Read csv file

In [41]:
import pandas as pd
subs=pd.read_csv('subs.csv')
print(subs)
type(subs)

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

pandas.core.frame.DataFrame

In [44]:
import pandas as pd
subs=pd.read_csv('subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [47]:
import pandas as pd
subs=pd.read_csv('subs.csv')
type(subs)

pandas.core.frame.DataFrame

In [48]:
import pandas as pd
subs=pd.read_csv('subs.csv',squeeze=True) # ('subs.csv').squeeze() if an error occure
print(subs)
type(subs)

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

pandas.core.series.Series

In [49]:
subs.min()

33

In [50]:
subs.max()

396

In [51]:
subs.median()

123.0

In [52]:
subs.sum()

49510

In [53]:
subs[subs>200]

165    225
166    249
167    265
168    306
169    261
170    222
225    224
226    254
227    214
228    236
229    261
230    247
231    207
232    254
233    301
234    233
240    202
246    259
248    213
249    210
252    216
275    228
276    237
277    276
279    290
280    295
281    245
282    241
283    267
284    269
285    211
287    206
288    202
290    236
291    222
292    203
312    230
318    244
324    243
325    227
326    259
330    396
331    312
332    268
333    229
337    221
338    225
339    221
340    202
344    276
345    258
346    219
347    212
351    220
354    204
358    210
359    209
360    231
361    226
Name: Subscribers gained, dtype: int64

In [54]:
subs[subs>200].size

59

In [59]:
a=pd.read_csv('bollywood.csv')
a

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [57]:
a.min()

movie    1920 (film)
lead      Aadar Jain
dtype: object

In [58]:
a.max()

movie    Zor Lagaa Ke...Haiya!
lead               Zulfi Sayed
dtype: object

In [62]:
a=pd.read_csv('bollywood.csv',index_col='movie',squeeze=True)
print(a)
print(type(a))

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object
<class 'pandas.core.series.Series'>

In [65]:
a.head(50)

movie
Uri: The Surgical Strike                       Vicky Kaushal
Battalion 609                                    Vicky Ahuja
The Accidental Prime Minister (film)             Anupam Kher
Why Cheat India                                Emraan Hashmi
Evening Shadows                             Mona Ambegaonkar
Soni (film)                             Geetika Vidya Ohlyan
Fraud Saiyaan                                   Arshad Warsi
Bombairiya                                      Radhika Apte
Manikarnika: The Queen of Jhansi              Kangana Ranaut
Thackeray (film)                         Nawazuddin Siddiqui
Amavas                                             Ali Asgar
Gully Boy                                      Ranveer Singh
Hum Chaar                                        Prit Kamani
Total Dhamaal                                     Ajay Devgn
Sonchiriya                              Sushant Singh Rajput
Badla (2019 film)                           Amitabh Bachchan
Mard Ko Dard Nahi Hota                      Abhimanyu Dasani
Hamid (film)                              Talha Arshad Reshi
Photograph (film)                        Nawazuddin Siddiqui
Risknamaa                                     Garima Agarwal
Mere Pyare Prime Minister                      Rasika Agashe
22 Yards                                         Barun Sobti
Kesari (film)                                   Akshay Kumar
Notebook (2019 film)                            Zaheer Iqbal
Junglee (2019 film)                           Vidyut Jammwal
Gone Kesh                                       Deepika Amin
Albert Pinto Ko Gussa Kyun Aata Hai?              Manav Kaul
The Tashkent Files                          Naseeruddin Shah
Kalank                                          Varun Dhawan
Setters (film)                               Shreyas Talpade
Student of the Year 2                           Tiger Shroff
PM Narendra Modi                                 Boman Irani
De De Pyaar De                                    Ajay Devgn
India's Most Wanted (film)                      Arjun Kapoor
Yeh Hai India                                   Gavie Chahal
Khamoshi (2019 film)                             Prabhu Deva
Kabir Singh                                    Shahid Kapoor
Article 15 (film)                         Ayushmann Khurrana
One Day: Justice Delivered                       Anupam Kher
Hume Tumse Pyaar Kitna                        Karanvir Bohra
Super 30 (film)                               Hrithik Roshan
Family of Thakurganj                         Jimmy Sheirgill
Batla House                                     John Abraham
Jhootha Kahin Ka                                Rishi Kapoor
Judgementall Hai Kya                          Kangana Ranaut
Chicken Curry Law                           Natalia Janoszek
Arjun Patiala                                 Diljit Dosanjh
Jabariya Jodi                              Sidharth Malhotra
Pranaam                                    Rajeev Khandelwal
The Sky Is Pink                                  Zaira Wasim
Name: lead, dtype: object

In [67]:
a.tail()

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [68]:
a.tail(20)

movie
Rules: Pyaar Ka Superhit Formula                 Tanuja
Right Here Right Now (film)                       Ankit
Raja Bhaiya (film)                  Sadashiv Amrapurkar
Tere Naam                                   Salman Khan
Tujhe Meri Kasam                       Riteish Deshmukh
Talaash: The Hunt Begins...               Rakhee Gulzar
Tehzeeb (2003 film)                        Shabana Azmi
The Pink Mirror                         Edwin Fernandes
Yeh Dil                                  Tusshar Kapoor
Xcuse Me                                  Sharman Joshi
Raaz (2002 film)                             Dino Morea
Zameen (2003 film)                           Ajay Devgn
Waisa Bhi Hota Hai Part II                 Arshad Warsi
Devdas (2002 Hindi film)                 Shah Rukh Khan
Kaante                                 Amitabh Bachchan
Hum Tumhare Hain Sanam                   Shah Rukh Khan
Aankhen (2002 film)                    Amitabh Bachchan
Saathiya (film)                            Vivek Oberoi
Company (film)                               Ajay Devgn
Awara Paagal Deewana                       Akshay Kumar
Name: lead, dtype: object

In [69]:
a[0]

'Vicky Kaushal'

In [73]:
a['Uri: The Surgical Strike']

'Vicky Kaushal'

In [74]:
a[::2]

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: object

In [75]:
a[[0,3,1,6,8]]

movie
Uri: The Surgical Strike             Vicky Kaushal
Why Cheat India                      Emraan Hashmi
Battalion 609                          Vicky Ahuja
Fraud Saiyaan                         Arshad Warsi
Manikarnika: The Queen of Jhansi    Kangana Ranaut
Name: lead, dtype: object

In [77]:
a[-5:0]

Series([], Name: lead, dtype: object)

In [78]:
'Fraud Saiyaan' in a

True

In [79]:
'Vicky Kaushal' in a.values

True