In [1]:
import pandas as pd
m=pd.read_csv('bollywood.csv',index_col='movie', squeeze=True)
print(m)

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [2]:
m.index

Index(['Uri: The Surgical Strike', 'Battalion 609',
       'The Accidental Prime Minister (film)', 'Why Cheat India',
       'Evening Shadows', 'Soni (film)', 'Fraud Saiyaan', 'Bombairiya',
       'Manikarnika: The Queen of Jhansi', 'Thackeray (film)',
       ...
       'Raaz (2002 film)', 'Zameen (2003 film)', 'Waisa Bhi Hota Hai Part II',
       'Devdas (2002 Hindi film)', 'Kaante', 'Hum Tumhare Hain Sanam',
       'Aankhen (2002 film)', 'Saathiya (film)', 'Company (film)',
       'Awara Paagal Deewana'],
      dtype='object', name='movie', length=1500)

In [3]:
m.values

array(['Vicky Kaushal', 'Vicky Ahuja', 'Anupam Kher', ..., 'Vivek Oberoi',
       'Ajay Devgn', 'Akshay Kumar'], dtype=object)

In [5]:
m[m.values=='Akshay Kumar'].size

48

In [6]:
m[m.values=='Akshay Kumar']

movie
Kesari (film)                           Akshay Kumar
Mission Mangal                          Akshay Kumar
Housefull 4                             Akshay Kumar
Good Newwz                              Akshay Kumar
Gold (2018 film)                        Akshay Kumar
Toilet: Ek Prem Katha                   Akshay Kumar
Airlift (film)                          Akshay Kumar
Baby (2015 Hindi film)                  Akshay Kumar
Singh Is Bliing                         Akshay Kumar
Gabbar Is Back                          Akshay Kumar
Gabbar Is Back                          Akshay Kumar
Brothers (2015 film)                    Akshay Kumar
Holiday: A Soldier Is Never Off Duty    Akshay Kumar
Entertainment (2014 film)               Akshay Kumar
The Shaukeens                           Akshay Kumar
Special 26                              Akshay Kumar
Once Upon ay Time in Mumbai Dobaara!    Akshay Kumar
Boss (2013 Hindi film)                  Akshay Kumar
Joker (2012 film)                       Akshay Kumar
Housefull 2                             Akshay Kumar
Thank You (2011 film)                   Akshay Kumar
Desi Boyz                               Akshay Kumar
Housefull (2010 film)                   Akshay Kumar
Khatta Meetha (2010 film)               Akshay Kumar
Tees Maar Khan (2010 film)              Akshay Kumar
Action Replayy                          Akshay Kumar
Blue (2009 film)                        Akshay Kumar
De Dana Dan                             Akshay Kumar
Singh Is Kinng                          Akshay Kumar
Tashan (film)                           Akshay Kumar
Bhool Bhulaiyaa                         Akshay Kumar
Namastey London                         Akshay Kumar
Welcome (2007 film)                     Akshay Kumar
Bhagam Bhag                             Akshay Kumar
Humko Deewana Kar Gaye                  Akshay Kumar
Phir Hera Pheri                         Akshay Kumar
Mere Jeevan Saathi (2006 film)          Akshay Kumar
Deewane Huye Paagal                     Akshay Kumar
Dosti: Friends Forever                  Akshay Kumar
Garam Masala (2005 film)                Akshay Kumar
Insan                                   Akshay Kumar
Aitraaz                                 Akshay Kumar
Hatya (2004 film)                       Akshay Kumar
Meri Biwi Ka Jawaab Nahin               Akshay Kumar
Police Force: An Inside Story           Akshay Kumar
Andaaz                                  Akshay Kumar
Andaaz                                  Akshay Kumar
Awara Paagal Deewana                    Akshay Kumar
Name: lead, dtype: object

In [8]:
m.value_counts()

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Sanjeev Bhaskar      1
Akanksha Puri        1
Joy Mukherjee        1
Manish Anand         1
Sulabha Arya         1
Name: lead, Length: 566, dtype: int64

In [10]:
m.value_counts(ascending=True)

Sulabha Arya         1
Manish Anand         1
Joy Mukherjee        1
Akanksha Puri        1
Sanjeev Bhaskar      1
                    ..
Sanjay Dutt         26
Salman Khan         31
Ajay Devgn          38
Amitabh Bachchan    45
Akshay Kumar        48
Name: lead, Length: 566, dtype: int64

In [12]:
x=m.value_counts()
x[x>20]

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: lead, dtype: int64

In [14]:
marks={'ram':55,'shyam':60,'seeta':66,'geeta':70}
marks_series=pd.Series(marks,name='student result')
print(marks_series)

ram      55
shyam    60
seeta    66
geeta    70
Name: student result, dtype: int64

In [15]:
list(marks_series)

[55, 60, 66, 70]

In [16]:
dict(marks_series)

{'ram': 55, 'shyam': 60, 'seeta': 66, 'geeta': 70}

In [17]:
marks_series[1]=100
marks_series

ram       55
shyam    100
seeta     66
geeta     70
Name: student result, dtype: int64

In [18]:
100+marks_series

ram      155
shyam    200
seeta    166
geeta    170
Name: student result, dtype: int64

In [20]:
marks_series>=100

ram      False
shyam     True
seeta    False
geeta    False
Name: student result, dtype: bool

In [23]:
a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a==b)
print(a>b)
print(a<b)

0     3
1     7
2    11
3    15
4    20
dtype: int64
0    1
1    1
2    1
3    1
4    0
dtype: int64
0      2
1     12
2     30
3     56
4    100
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64
0    False
1    False
2    False
3    False
4     True
dtype: bool
0     True
1     True
2     True
3     True
4    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool

0    False
1    False
2    False
3    False
4     True
dtype: bool
0     True
1     True
2     True
3     True
4    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool

# > DATA FRAME :

- Pandas dataframe is a 2-D data structure like a 2-D array or a table with rows and columns

In [24]:
import pandas as pd

In [25]:
data={'calories':[400,420,380,390],'duration':[50,40,45,60]}
df=pd.DataFrame(data)
df

   calories  duration
0       400        50
1       420        40
2       380        45
3       390        60

In [26]:
print(df)

   calories  duration
0       400        50
1       420        40
2       380        45
3       390        60

In [27]:
df.loc[0]

calories    400
duration     50
Name: 0, dtype: int64

In [29]:
df.iloc[0]

calories    400
duration     50
Name: 0, dtype: int64

In [31]:
data={'calories':[400,420,380,390],'duration':[50,40,45,60]}
df=pd.DataFrame(data,index=['day1','day2','day3','day4'])

In [32]:
df.iloc[0]

calories    400
duration     50
Name: day1, dtype: int64

In [33]:
df.loc[0]

KeyError: 0

In [34]:
df.loc['day1']

calories    400
duration     50
Name: day1, dtype: int64

In [35]:
df.iloc['day1']

TypeError: Cannot index by location index with a non-integer key

In [36]:
df[::2]

      calories  duration
day1       400        50
day3       380        45

In [38]:
data={'name':['alice','bob','charlie'],
      'age':[25,30,35],
      'city':['nyc','la','chicago']}
fd=pd.DataFrame(data)
fd

      name  age     city
0    alice   25      nyc
1      bob   30       la
2  charlie   35  chicago

In [41]:
fd.loc[0:2]

      name  age     city
0    alice   25      nyc
1      bob   30       la
2  charlie   35  chicago

In [42]:
fd.iloc[0:2]

    name  age city
0  alice   25  nyc
1    bob   30   la

In [71]:
data={'a':[1,2,3,4],
     'b':[5,6,7,8]}
d=pd.DataFrame(data,index=['r1','r2','r3','r4'])
d

    a  b
r1  1  5
r2  2  6
r3  3  7
r4  4  8

In [72]:
d.loc['r2':'r4' , 'b']=99
d

    a   b
r1  1   5
r2  2  99
r3  3  99
r4  4  99

In [73]:
d.iloc[1:3 , 0]=0
d

    a   b
r1  1   5
r2  0  99
r3  0  99
r4  4  99

In [74]:
d['c']=[10,20,30,40]
d

    a   b   c
r1  1   5  10
r2  0  99  20
r3  0  99  30
r4  4  99  40

In [75]:
d.loc[d['a']==0,'d']='zero'
d

    a   b   c     d
r1  1   5  10   NaN
r2  0  99  20  zero
r3  0  99  30  zero
r4  4  99  40   NaN

In [76]:
d.loc[len(d)]=[10,20,30,40]
d

     a   b   c     d
r1   1   5  10   NaN
r2   0  99  20  zero
r3   0  99  30  zero
r4   4  99  40   NaN
4   10  20  30    40

**- Set_index() :**
- used to set one or more columns of a dataframe as the index

In [87]:
data={'name':['alice','bob','charlie'],
      'age':[25,30,35],
      'city':['nyc','la','chicago']}
df=pd.DataFrame(data)
df.set_index('name',drop=False)

            name  age     city
name
alice      alice   25      nyc
bob          bob   30       la
charlie  charlie   35  chicago

In [88]:
df

      name  age     city
0    alice   25      nyc
1      bob   30       la
2  charlie   35  chicago

In [89]:
df.set_index('name',drop=False,inplace=True)

In [90]:
df

            name  age     city
name
alice      alice   25      nyc
bob          bob   30       la
charlie  charlie   35  chicago

In [91]:
df1=df.set_index(['name','age'],drop=False)

In [92]:
df1

                name  age     city
name    age
alice   25     alice   25      nyc
bob     30       bob   30       la
charlie 35   charlie   35  chicago

**- reset_index() :**
- used to manage and reset the index of a dataframe

In [98]:
data={'name':['alice','bob','charlie'],
      'age':[25,30,35],
      'city':['nyc','la','chicago']}
f1=pd.DataFrame(data,index=['a','b','c'])
f1

      name  age     city
a    alice   25      nyc
b      bob   30       la
c  charlie   35  chicago

In [99]:
f_reset=f1.reset_index()
f_reset

  index     name  age     city
0     a    alice   25      nyc
1     b      bob   30       la
2     c  charlie   35  chicago

In [100]:
f_reset=f1.reset_index(drop=True)
f_reset

      name  age     city
0    alice   25      nyc
1      bob   30       la
2  charlie   35  chicago

**- DataFrame Attributea :**

In [101]:
f1.index

Index(['a', 'b', 'c'], dtype='object')

In [102]:
f1.columns

Index(['name', 'age', 'city'], dtype='object')

In [103]:
f1.size

9

In [104]:
f.values

array([['alice', 25, 'nyc'],
       ['bob', 30, 'la'],
       ['charlie', 35, 'chicago']], dtype=object)

In [105]:
f1.dtypes

name    object
age      int64
city    object
dtype: object

In [106]:
f1.ndim

2

In [107]:
f1.shape

(3, 3)

In [109]:
a=pd.read_csv('auto-mpg.csv')
print(a)

      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]

In [111]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [112]:
a.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [113]:
a.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite