# Drop and Remove duplicates

In [1]:
import pandas as pd

In [2]:
data={'a':['TeamA','TeamB','TeamB','Teamc','TeamA'],
      'b':[50,40,40,30,50],
       'c':[True,False,False,False,True]}
df=pd.DataFrame(data)
df

       a   b      c
0  TeamA  50   True
1  TeamB  40  False
2  TeamB  40  False
3  Teamc  30  False
4  TeamA  50   True

In [3]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [4]:
df.duplicated(keep='first') # CHeck from first

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [5]:
df.duplicated(keep='last') # CHeck from last

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [6]:
df.duplicated(keep=False) # gives True in all duplicates

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [7]:
df.drop_duplicates()

       a   b      c
0  TeamA  50   True
1  TeamB  40  False
3  Teamc  30  False

In [8]:
df.drop_duplicates(keep='first')

       a   b      c
0  TeamA  50   True
1  TeamB  40  False
3  Teamc  30  False

In [9]:
df.drop_duplicates(keep='last')

       a   b      c
2  TeamB  40  False
3  Teamc  30  False
4  TeamA  50   True

In [10]:
df.drop_duplicates(keep=False)

       a   b      c
3  Teamc  30  False

In [15]:
df.drop_duplicates(keep='first',inplace=True)

In [16]:
df.reset_index(drop=True)

       a   b      c
0  TeamA  50   True
1  TeamB  40  False
2  Teamc  30  False

# sort_values()

In [17]:
data={'name':["alice","bob","charlie","david"],
     'score':[88,92,95,90]}
df=pd.DataFrame(data)
df

      name  score
0    alice     88
1      bob     92
2  charlie     95
3    david     90

In [18]:
sorted_df=df.sort_values(by="score")
sorted_df

      name  score
0    alice     88
3    david     90
1      bob     92
2  charlie     95

In [19]:
sorted_df=df.sort_values(by="score" , ascending=False)
sorted_df

      name  score
2  charlie     95
1      bob     92
3    david     90
0    alice     88

In [20]:
df.sort_index(ascending=False)

      name  score
3    david     90
2  charlie     95
1      bob     92
0    alice     88

In [27]:
data={'name':["alice","bob","charlie","david"],
     'score':[88,92,95,90]}
df=pd.DataFrame(data)
df

      name  score
0    alice     88
1      bob     92
2  charlie     95
3    david     90

In [28]:
df.set_index('name',inplace=True)

In [29]:
df

         score
name
alice       88
bob         92
charlie     95
david       90

In [30]:
df.sort_index(ascending=False)

         score
name
david       90
charlie     95
bob         92
alice       88

# apply()

In [31]:
s=pd.Series([35,67,90,45])
def pass_fail(x):
    return "pass" if x>=50 else "fail"

result=s.apply(pass_fail)
print(result)

0    fail
1    pass
2    pass
3    fail
dtype: object

In [43]:
df=pd.DataFrame({
    'Physics':[60,80,80],
    'Chemistry':[65,75,85],
    'Maths':[70,80,90]
})
df

   Physics  Chemistry  Maths
0       60         65     70
1       80         75     80
2       80         85     90

In [35]:
result=df.apply(sum)
print(result)

Physics      220
Chemistry    225
Maths        240
dtype: int64

In [36]:
result=df.apply(sum,axis=1)
print(result)

0    195
1    235
2    255
dtype: int64

In [38]:
df=pd.DataFrame({
    'Physics':[60,70,80],
    'Chemistry':[65,75,85],
    'Maths':[70,80,90]
})

result=df.apply(lambda x:x.mean())
print(result)

Physics      70.0
Chemistry    75.0
Maths        80.0
dtype: float64

In [42]:
df

   Physics  Chemistry  Maths  total
0       60         65     70    390
1       70         75     80    450
2       80         85     90    510

In [44]:
df['total']=df.apply(lambda x:x.sum(),axis=1)
df

   Physics  Chemistry  Maths  total
0       60         65     70    195
1       80         75     80    235
2       80         85     90    255

In [45]:
def grade(total):
    if total>=250:
        return 'A'
    elif total>=200:
        return 'B'
    else:
        return 'C'

In [48]:
df['grade']=df['total'].apply(grade)
df

   Physics  Chemistry  Maths  total grade
0       60         65     70    195     C
1       80         75     80    235     B
2       80         85     90    255     A

## Raw parameter :
- less time consuming
- pass the data as an array

In [51]:
df=pd.DataFrame({
    'width':[1,2],'height':[3,4]
})

def get_stats(row):
    return [row['width']*row['height'],2*(row['width']+row['height'])]
df

   width  height
0      1       3
1      2       4

In [52]:
df.apply(get_stats,axis=1)

0     [3, 8]
1    [8, 12]
dtype: object

In [53]:
df.apply(get_stats,axis=1,result_type='expand')

   0   1
0  3   8
1  8  12

In [54]:
df.apply(get_stats,axis=1,result_type='reduce')

0     [3, 8]
1    [8, 12]
dtype: object

In [55]:
df.apply(get_stats,axis=1,result_type='broadcast')

   width  height
0      3       8
1      8      12

# Args and Kwargs parameters

In [56]:
def add_values(x,y,z):
    return x+y+z

df=pd.DataFrame({'A':[1,2],'B':[10,20]})

d=df.apply(add_values,args=(1,2))

print(d)

   A   B
0  4  13
1  5  23

In [59]:
def multiply_by_m(x,m):
    return x*m

df=pd.DataFrame({'A':[1,2],'B':[10,20]})

d=df.apply(multiply_by_m,m=2)

print(d)

   A   B
0  2  20
1  4  40

### astype() function

In [60]:
df=pd.DataFrame({'A':['1','2','3'],'B':['4','5','6']})
print(df.dtypes)

A    object
B    object
dtype: object

In [62]:
df['A']=df['A'].astype(int)
print(df.dtypes)

A     int32
B    object
dtype: object

### replace() function

In [63]:
df=pd.DataFrame({
    'Marks':[80,85,0,90],
    'Attendance':[75,80,0,85],
    'Grade':['A','B','F','D']
})
print(df)
result=df.replace([80,75],[90,80])
print(result)

   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2      0           0     F
3     90          85     D
   Marks  Attendance Grade
0     90          80     A
1     85          90     B
2      0           0     F
3     90          85     D

In [64]:
df=pd.DataFrame({
    'Marks':[80,85,0,90],
    'Attendance':[75,80,0,85],
    'Grade':['A','B','F','D']
})
result=df.replace({80:90},{85:80})
print(result)

   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2      0           0     F
3     90          85     D

In [65]:
df=pd.DataFrame({
    'Marks':[80,85,0,90],
    'Attendance':[75,80,0,85],
    'Grade':['A','B','F','D']
})
print(df)
result=df.replace(0,95)
print(result)

   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2      0           0     F
3     90          85     D
   Marks  Attendance Grade
0     80          75     A
1     85          80     B
2     95          95     F
3     90          85     D

In [68]:
df['Marks']=df['Marks'].replace(80,85)
df

   Marks  Attendance Grade
0     85          75     A
1     85          80     B
2     85           0     F
3     90          85     D

## concat() function

In [78]:
d1=pd.DataFrame({'A':[1,2],'B':[3,4]})
d2=pd.DataFrame({'A':[5,6],'C':[7,8]})

r=pd.concat([d1,d2],axis=0)
r

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [72]:
d1=pd.DataFrame({'A':[1,2],'B':[3,4]})
d2=pd.DataFrame({'A':[5,6],'C':[7,8]})

r=pd.concat([d1,d2],axis=1)
r

   A  B  A  C
0  1  3  5  7
1  2  4  6  8

In [73]:
r=pd.concat([d1,d2],join='outer') # keeps all col and rows
r

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [74]:
r=pd.concat([d1,d2],join='inner') # only keeps common/overlap col and rows
r

   A
0  1
1  2
0  5
1  6

In [75]:
r=pd.concat([d1,d2],join='inner',ignore_index=True) 
r

   A
0  1
1  2
2  5
3  6

In [80]:
d1=pd.DataFrame({'A':[1,2],'B':[3,4]})
d2=pd.DataFrame({'C':[5,6],'D':[7,8]})

r=pd.concat([d1,d2],sort=True) 
r

     A    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

In [82]:
r=pd.concat([d1,d2],sort=False) 
r

     A    B    C    D
0  1.0  3.0  NaN  NaN
1  2.0  4.0  NaN  NaN
0  NaN  NaN  5.0  7.0
1  NaN  NaN  6.0  8.0

In [83]:
r=pd.concat([d1,d2],sort=False,axis=1) 
r

   A  B  C  D
0  1  3  5  7
1  2  4  6  8

# merge()  function

In [84]:
d1=pd.DataFrame({
    'Employee':['A' , 'B' , 'C'],
    'Department':['IT','HR','Finance']
})

d2=pd.DataFrame({
    'Employee':['A' , 'B' , 'D'],
    'salary':[50000,40000,30000]
})

r=pd.merge(d1,d2,on='Employee',how='inner')
print(r)

  Employee Department  salary
0        A         IT   50000
1        B         HR   40000

In [85]:
r=pd.merge(d1,d2,on='Employee',how='outer')
print(r)

  Employee Department   salary
0        A         IT  50000.0
1        B         HR  40000.0
2        C    Finance      NaN
3        D        NaN  30000.0