In [1]:
import pandas as pd

In [3]:
a1=pd.DataFrame({
    'id':[1,2,3],
    'name':['amit','riya','john'],
    'salary':[50000,60000,55000]
})
a2=pd.DataFrame({
    'id':[1,2,4],
    'name':['amit','riya','dravid'],
    'salary':[50000,60000,58000]
})

r=pd.merge(a1,a2,on='id',suffixes=("_a1","_a2"))
print(r)

   id name_a1  salary_a1 name_a2  salary_a2
0   1    amit      50000    amit      50000
1   2    riya      60000    riya      60000

- how="inner" --> gives common elements
- how="outer" --> gives all elements

In [5]:
d1=pd.DataFrame({
    "student_id":[1,2,3],
    "name":['Amit','Riya','John']
})
d2=pd.DataFrame({
    "id":[1,2,4],
    "marks":[85,90,75]
})
r=pd.merge(d1,d2,left_on='student_id',right_on='id')
print(r)

   student_id  name  id  marks
0           1  Amit   1     85
1           2  Riya   2     90

In [11]:
d1=pd.DataFrame({
    "physics":[70,80,90]},
    index=[101,102,103]
)
d2=pd.DataFrame({
    "name":['alice','bob','charlie']},
     index=[101,102,103])
    
r=pd.merge(d1,d2,left_index=True,right_index=True)
print(r)

     physics     name
101       70    alice
102       80      bob
103       90  charlie

In [12]:
d1=pd.DataFrame({
    "student_id":[1,2,3],
    "name":['Amit','Riya','John']
})
d2=pd.DataFrame({
    "score":[80,90,70]},
     index=[1,2,3])

r=pd.merge(d1,d2,left_on='student_id',right_index=True)
print(r)

   student_id  name  score
0           1  Amit     80
1           2  Riya     90
2           3  John     70

# groupby() function

In [14]:
data={'product':['electronics','furniture','electronics','furniture'],
     'sales':[200,150,300,100]}
df=pd.DataFrame(data)

       product  sales
0  electronics    200
1    furniture    150
2  electronics    300
3    furniture    100

In [17]:
r=df.groupby('product')['sales'].sum()
print(r)

product
electronics    500
furniture      250
Name: sales, dtype: int64

In [18]:
r=df.groupby('product')['sales'].mean()
print(r)

product
electronics    250
furniture      125
Name: sales, dtype: int64

In [19]:
r=df.groupby('product')['sales'].median()
print(r)

product
electronics    250
furniture      125
Name: sales, dtype: int64

In [20]:
r=df.groupby('product')['sales'].describe()
print(r)

             count   mean        std    min    25%    50%    75%    max
product
electronics    2.0  250.0  70.710678  200.0  225.0  250.0  275.0  300.0
furniture      2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0

In [22]:
r=df.groupby('product')['sales'].sample()
print(r)

2    300
3    100
Name: sales, dtype: int64

In [23]:
r=df.groupby('product')['sales'].size()
print(r)

product
electronics    2
furniture      2
Name: sales, dtype: int64

In [24]:
r=df.groupby('product')['sales'].groups
print(r)

{'electronics': [0, 2], 'furniture': [1, 3]}

In [25]:
r=df.groupby('product')['sales'].nunique()
print(r)

product
electronics    2
furniture      2
Name: sales, dtype: int64

In [26]:
r=df.groupby('product')['sales'].nth(0)
print(r)

product
electronics    200
furniture      150
Name: sales, dtype: int64

In [27]:
r=df.groupby('product')['sales'].nth(1)
print(r)

product
electronics    300
furniture      100
Name: sales, dtype: int64

In [28]:
r=df.groupby('product',axis=0,as_index=True,sort=True)['sales'].count()
print(r)

product
electronics    2
furniture      2
Name: sales, dtype: int64

In [29]:
r=df.groupby('product',axis=0,as_index=False,sort=True)['sales'].count()
print(r)

       product  sales
0  electronics      2
1    furniture      2

In [30]:
df=pd.DataFrame({
    'Region':['East','East','West','West','East','West'],
    'sales':[100,150,200,120,110,130],
    'Manager':['A','B','C','D','E','F']
})
df

  Region  sales Manager
0   East    100       A
1   East    150       B
2   West    200       C
3   West    120       D
4   East    110       E
5   West    130       F

In [33]:
def sales_range(group):
    return group['sales'].max()-group['sales'].min()
sales=df.groupby('Region').apply(sales_range)
print(sales)

Region
East    50
West    80
dtype: int64

In [35]:
df=pd.DataFrame({
    'dept':['sales','sales','HR','HR','IT','IT'],
    'salary':[50000,60000,40000,45000,70000,75000],
    'bonus':[5000,6000,2000,2500,8000,5800]
})
r=df.groupby('dept').agg('mean')
print(r)

       salary  bonus
dept
HR      42500   2250
IT      72500   6900
sales   55000   5500

In [37]:
df=pd.DataFrame({
    'dept':['sales','sales','HR','HR','IT','IT'],
    'salary':[50000,60000,40000,45000,70000,75000],
    'bonus':[5000,6000,2000,2500,8000,5800]
})
r=df.groupby('dept').agg(['mean','min','max'])
print(r)

      salary               bonus
        mean    min    max  mean   min   max
dept
HR     42500  40000  45000  2250  2000  2500
IT     72500  70000  75000  6900  5800  8000
sales  55000  50000  60000  5500  5000  6000

In [38]:
df=pd.DataFrame({
    'dept':['sales','sales','HR','HR','IT','IT'],
    'salary':[50000,60000,40000,45000,70000,75000],
    'bonus':[5000,6000,2000,2500,8000,5800]
})
r=df.groupby('dept').agg({'salary':['mean','max'],
                          'bonus':['sum']})
print(r)

      salary         bonus
        mean    max    sum
dept
HR     42500  45000   4500
IT     72500  75000  13800
sales  55000  60000  11000

In [39]:
df=pd.DataFrame({
    'dept':['sales','sales','HR','HR','IT','IT'],
    'salary':[50000,60000,40000,45000,70000,75000],
    'bonus':[5000,6000,2000,2500,8000,8500]
})
r=df.groupby('dept').agg(Meansalary=('salary','mean'),
                        maxsalary=('salary','max'),
                        totalbonus=('bonus','sum'))
print(r)

       Meansalary  maxsalary  totalbonus
dept
HR          42500      45000        4500
IT          72500      75000       16500
sales       55000      60000       11000