In [1]:
import requests
from bs4 import BeautifulSoup

url = 'https://www.politifact.com/factchecks/'
result=requests.get(url)
content=result.text
soup=BeautifulSoup(content,'html.parser')
print(soup.prettify())

# result.status_code

<!DOCTYPE html>
<html dir="ltr" lang="en-US">
 <head>
  <meta charset="utf-8"/>
  <meta content="ie=edge" http-equiv="x-ua-compatible"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Fact-checks | PolitiFact
  </title>
  <meta content="PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter." name="description">
   <meta content="all" name="robots">
    <meta content="PolitiFact" name="publisher"/>
    <meta content="PolitiFact" name="twitter:username">
     <meta content="summary" name="twitter:card">
      <meta content="PolitiFact" name="twitter:site"/>
      <meta content="" name="twitter:url">
       <meta content="" name="twitter:title"/>
       <meta content="PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter." name="twitter:description"/>
       <meta content="vrxxsw8mwnf2pxgnwxvgsn4g93w3vm" name="facebook-domain-verification"/>
       <link href="https://static.politifact.com/images/favicon.ico" rel="shortcut icon" type="image/ico"/>
       <link href="https://static.politifact.com/images/favicon.png" rel="icon" type="image/png"/>
       <link href="https://static.politifact.com/images/apple-touch-icon.png" rel="apple-touch-icon"/>
       <link href="/rss/social/" rel="alternate" title="Latest Fact-checks and Articles" type="application/rss+xml">
        <link href="/rss/factchecks/" rel="alternate" title="Latest Fact-checks" type="application/rss+xml">
         <script src="https://static.politifact.com/js/sharethefacts-v1.js">
         </script>
         <script src="//d283fm003ll1xs.cloudfront.net/script.js" type="text/javascript">
         </script>
         <script>
          !(function () { window.googletag = window.googletag || {}; window.vmpbjs = window.vmpbjs || {}; window.vpb = window.vpb || {}; vpb.cmd = vpb.cmd || []; vpb.st=Date.now();  vpb.fastLoad = true; googletag.cmd = googletag.cmd || []; vmpbjs.cmd = vmpbjs.cmd || []; var cmds = []; try{ cmds = googletag.cmd.slice(0); googletag.cmd.length = 0; }catch(e){} var ready = false; function exec(cb) { return cb.call(googletag); } var overriden = false; googletag.cmd.push(function () { overriden = true; googletag.cmd.unshift = function (cb) { if (ready) { return exec(cb); } cmds.unshift(cb); if (cb._startgpt) { ready = true; for (var k = 0; k < cmds.length; k++) { exec(cmds[k]); } } }; googletag.cmd.push = function (cb) { if (ready) { return exec(cb); } cmds.push(cb); }; }); if(!overriden){ googletag.cmd.push = function (cb) { cmds.push(cb); }; googletag.cmd.unshift = function (cb) { cmds.unshift(cb); if (cb._startgpt) { ready = true; if (googletag.apiReady) { cmds.forEach(function (cb) { googletag.cmd.push(cb); }); } else { googletag.cmd = cmds; } } }; } var dayMs = 36e5, cb = parseInt(Date.now() / dayMs), vpbSrc = '//player.hbmp.ops.co/prebidlink/' + cb + '/wrapper_hb_779253_23204.js', pbSrc = vpbSrc.replace('wrapper_hb', 'hb'), gptSrc = '//securepubads.g.doubleclick.net/tag/js/gpt.js', c = document.head || document.body || document.documentElement; function loadScript(src, cb) { var s = document.createElement('script'); s.src = src; s.defer=false; c.appendChild(s); s.onload = cb; s.onerror = function(){ var fn = function(){}; fn._startgpt = true; googletag.cmd.unshift(fn); }; return s; } loadScript(pbSrc); loadScript(gptSrc); loadScript(vpbSrc); })()
         </script>
         <script>
          window.googletag = window.googletag || {cmd: []};
  googletag.cmd.push(function() {
    const sizeMapping = googletag.sizeMapping()
        .addSize([1440, 0], [
            [970,90],
            [970,250],
            [728,90],
        ])
        .addSize([1024, 0], [
            [728,90],
            [320,100],
        ])
        .addSize([768, 0], [
            [320, 50],
            [300, 50],
        ])
        .addSize([0, 0], [
            [320, 50],
			[300, 50],
        ])
        .build();
    googletag.defineSlot('/25722649/Politifact/BottomLeaderboard_Adhesion', [[300,50],[320,50],[728,90]], 'BottomLeaderboard_Adhesion')
      .defineSizeMapping(sizeMapping)
      .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_BottomLeaderboard', [[320,50],[728,90]], 'BottomLeaderboard')
      .defineSizeMapping(sizeMapping)
      .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_MiddleRectangle', [[300,250]], 'MiddleRectangle')
             .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_TopLeaderboard', [[320,50],[728,90]], 'TopLeaderboard')
      .defineSizeMapping(sizeMapping)
      .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_TopMedRect', [[300,250],[300,600]], 'TopMedRect')
             .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/SmartNewsFeed', [[300,250]], 'SmartNewsFeed')
             .addService(googletag.pubads());

    googletag.pubads().enableSingleRequest();
    googletag.enableServices();
  });
         </script>
         <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-35156640-2">
         </script>
         <script>
          window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-35156640-2');
         </script>
         <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-EDXB0TJGGY">
         </script>
         <script>
          window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-EDXB0TJGGY');
         </script>
         <script async="" id="ebx" src="//applets.ebxcdn.com/ebx.js">
         </script>
         <div id="fb-root">
         </div>
         <script>
          (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
         </script>
         <!-- End Facebook Pixel Code -->
         <noscript>
          <img height="1" src="//www.facebook.com/tr?id=292850974235854&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/>
         </noscript>
         <link href="https://static.politifact.com/assets/main-CiDydm0l.css" rel="stylesheet">
          <style>
           .m-notfound{padding-top:2.5rem;padding-bottom:3.5rem}@media print, screen and (min-width: 48em){.m-notfound{padding-top:5rem;padding-bottom:6rem}}.m-notfound__title{margin-bottom:2.5rem;text-align:center}@media print, screen and (min-width: 48em){.m-notfound__content{display:-webkit-box;display:-ms-flexbox;display:flex}}.m-notfound__image{margin-bottom:1.5rem;margin-left:auto;margin-right:auto;max-width:10rem}@media print, screen and (min-width: 48em){.m-notfound__image{-webkit-box-flex:0;-ms-flex:0 0 13.75rem;flex:0 0 13.75rem;max-width:none}}.m-notfound__body{padding-top:.5rem}@media print, screen and (min-width: 48em){.m-notfound__body{padding-left:2rem}}.m-notfound__body p{margin-top:0}
          </style>
         </link>
        </link>
       </link>
      </meta>
     </meta>
    </meta>
   </meta>
  </meta>
 </head>
 <body class="" data-role="page">
  <div class="global-wrapper" id="top">
   <header class="o-header">
    <div class="o-header__inner">
     <div class="o-header__branding">
      <a href="/">
       <span class="m-branding">
        <span class="m-branding__logo">
         <svg class="c-icon">
          <use xlink:href="#svg_logo-plain">
          </use>
         </svg>
        </span>
        <span class="m-branding__subline">
         <span class="m-branding__claim">
          The Poynter Institute
         </span>
        </span>
       </span>
      </a>
     </div>
     <div class="o-header__menu">
      <a class="c-burger" data-menu-toggle="" href="#">
       <span class="c-burger__lines">
       </span>
       <span class="c-burger__value">
        Menu
       </span>
      </a>
     </div>
     <div class="o-header__donate">
      <a class="c-button c-button--small show-for-large" href="/membership/">
       Donate
      </a>
     </div>
    </div>
    <div class="t-menu" data-menu="">
     <div class="t-menu__content">
      <div class="o-menu-list">
       <div class="o-menu-list__inner">
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_1" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_1" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_1" role="tab">
           State Editions
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_1" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/california/">
              California
             </a>
            </li>
            <li>
             <a href="/florida/">
              Florida
             </a>
            </li>
            <li>
             <a href="/iowa/">
              Iowa
             </a>
            </li>
            <li>
             <a href="/michigan/">
              Michigan
             </a>
            </li>
            <li>
             <a href="/new-hampshire/">
              New Hampshire
             </a>
            </li>
            <li>
             <a href="/new-york/">
              New York
             </a>
            </li>
            <li>
             <a href="/north-carolina/">
              North Carolina
             </a>
            </li>
            <li>
             <a href="/pennsylvania/">
              Pennsylvania
             </a>
            </li>
            <li>
             <a href="/texas/">
              Texas
             </a>
            </li>
            <li>
             <a href="/west-virginia/">
              West Virginia
             </a>
            </li>
            <li>
             <a href="/wisconsin/">
              Wisconsin
             </a>
            </li>
            <li>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_2" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_2" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_2" role="tab">
           Issues
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_2" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <strong>
              <a href="/issues/">
               All Issues
              </a>
             </strong>
            </li>
            <li>
             <a href="/factchecks/list/?speaker_type=SOCIAL">
              Online hoaxes
             </a>
            </li>
            <li>
             <a href="/coronavirus/">
              Coronavirus
             </a>
            </li>
            <li>
             <a href="/health-check/">
              Health Care
             </a>
            </li>
            <li>
             <a href="/immigration/">
              Immigration
             </a>
            </li>
            <li>
             <a href="https://www.politifact.com/article/2022/jun/09/political-extremism-public-square-resource-journal/">
              Extremism
             </a>
            </li>
            <li>
             <a href="/taxes/">
              Taxes
             </a>
            </li>
            <li>
             <a href="/marijuana/">
              Marijuana
             </a>
            </li>
            <li>
             <a href="/environment/">
              Environment
             </a>
            </li>
            <li>
             <a href="/crime/">
              Crime
             </a>
            </li>
            <li>
             <a href="/guns/">
              Guns
             </a>
            </li>
            <li>
             <a href="/foreign-policy/">
              Foreign Policy
             </a>
            </li>
            <li>
             <a href="/lgbtq/">
              LGBTQ+
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_3" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_3" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_3" role="tab">
           People
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_3" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/personalities/donald-trump/">
              Donald Trump
             </a>
            </li>
            <li>
             <a href="/personalities/jd-vance/">
              JD Vance
             </a>
            </li>
            <li>
             <a href="/personalities/mitch-mcconnell/">
              Mitch McConnell
             </a>
            </li>
            <li>
             <a href="/personalities/mike-johnson/">
              Mike Johnson
             </a>
            </li>
            <li>
             <a href="/personalities/joe-biden/">
              Joe Biden
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_4" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_4" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_4" role="tab">
           Media
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_4" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/punditfact/">
              PunditFact
             </a>
            </li>
            <li>
             <a href="/personalities/tucker-carlson/">
              Tucker Carlson
             </a>
            </li>
            <li>
             <a href="/personalities/sean-hannity/">
              Sean Hannity
             </a>
            </li>
            <li>
             <a href="/personalities/rachel-maddow/">
              Rachel Maddow
             </a>
            </li>
            <li>
             <a href="/personalities/blog-posting/">
              Bloggers
             </a>
            </li>
            <li>
             <a href="/videos/">
              PolitiFact Videos
             </a>
            </li>
           </ul>
          </div>
         </div>
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_5" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_5" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_5" role="tab">
           Campaigns
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_5" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/elections/">
              2024 Elections
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_6" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_6" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_6" role="tab">
           Truth-o-Meter
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_6" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/factchecks/list/?ruling=true">
              True
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=mostly-true">
              Mostly True
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=half-true">
              Half True
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=barely-true">
              Mostly False
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=false">
              False
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=pants-fire">
              Pants on Fire
             </a>
            </li>
           </ul>
          </div>
         </div>
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_7" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_7" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_7" role="tab">
           Promises
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_7" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/truth-o-meter/promises/maga-meter-tracking-donald-trumps-2024-promises/?ruling=true">
              MAGA-Meter
             </a>
            </li>
            <li>
             <a href="/truth-o-meter/promises/biden-promise-tracker/?ruling=true">
              Biden Promise Tracker
             </a>
            </li>
            <li>
             <a href="/truth-o-meter/promises/trumpometer/?ruling=true">
              Trump-O-Meter
             </a>
            </li>
            <li>
             <a href="/truth-o-meter/promises/obameter/?ruling=true">
              Obameter
             </a>
             <li>
              <a href="/truth-o-meter/promises/list/">
               Latest Promises
              </a>
             </li>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_8" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_8" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_8" role="tab">
           About Us
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_8" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/ ">
              Our Process
             </a>
            </li>
            <li>
             <a href="/staff/">
              Our Staff
             </a>
            </li>
            <li>
             <a href="/espanol/">
              En Español
             </a>
            </li>
            <li>
             <a href="/who-pays-for-politifact/">
              Who pays for PolitiFact?
             </a>
            </li>
            <li>

In [2]:
data = soup.find_all('li',class_ = 'o-listicle__item')
data

[<li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--false">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/80bd15ec0d50cf908299031c9790109e.jpg" width="83"/>
 <picture>
 <img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c1c32c5a2e0a94447f75d2e6dfe5573d.jpg" width="166"/>
 </picture>
 </div>
 </div>
 </div>
 <div class="m-statement__meta">
 <a class="m-statement__name" href="/personalities/donald-trump/" title="Donald Trump">
                     Donald Trump
                   </a>
 <div class="m-statement__desc">
                     stated on May 18, 2026 in remarks at the White House:
                   </div>
 </div>
 </div>
 <div class="m-statement__content">
 <div class="m-statement__body">
 <div class="m-statement__quote-wrap">
 <div class="m-statement__quote">
 <a href="/factchecks/2026/may/20/donald-trump/legal-settlement-fund-weaponization-justice-jan-6/">

                         "There's been numerous other occasions over the years” when the federal government created a reserve similar to a new $1.776 billion anti-weaponization settlement fund.

                       </a>
 </div>
 </div>
 <div class="m-statement__meter">
 <div class="c-image" style="padding-top: 89.49771689497716%;">
 <img alt="false" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-false-th.jpg" width="219"/>
 <picture>
 <img alt="false" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-false.jpg" width="219"/>
 </picture>
 </div>
 </div>
 <footer class="m-statement__footer">
                     By Louis Jacobson • May 20, 2026
                   </footer>
 </div>
 </div>
 </article>
 </li>,
 <li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--false">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/Social_media_apps_shutterstock/3773b507a544b9625369bf10fcd6c213.jpg" width="83"/>
 <picture>
 <img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/Social_media_apps_shutterstock/2189518027d0806055e97ed66491ccdf.jpg" width="166"/>
 </picture>
 </div>
 </div>
 </div>
 <div class="m-statement__meta">
 <a class="m-statement__name" href="/personalities/social-media/" title="Social Media">
                     Social Media
                   </a>
 <div class="m-statement__desc">
                     stated on May 19, 2026 in in social media posts:
                   </div>
 </div>
 </div>
 <div class="m-statement__content">
 <div class="m-statement__body">
 <div class="m-statement__quote-wrap">
 <div class="m-statement__quote">
 <a href="/factchecks/2026/may/20/social-media/no-evidence-san-diego-mosque-suspects-trans/">

                         “San Diego mosque shooters identified as trans couple.”

                       </a>
 </div>
 </div>
 <div class="m-statement__meter">
 <div class="c-image" style="padding-top: 89.49771689497716%;">
 <img alt="false" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-false-th.jpg" width="219"/>
 <picture>
 <img alt="false" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-false.jpg" width="219"/>
 </picture>
 </div>
 </div>
 <footer class="m-statement__footer">
                     By Jeff Cercone • May 20, 2026
                   </footer>
 </div>
 </div>
 </article>
 </li>,
 <li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--fire">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/logo-black/4590875651af69b2c789ceab409664dd.jpg" width="83"/>
 <picture>
 <img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/logo-black/72988380e8c8bd188dc360d11552e4a0.jpg" width="166"/>
 </picture>
 </div>
 </div>
 </div>
 <div class="m-statement__meta">
 <a class="m-statement__name" href="/personalities/tweets/" title="X posts">
                      X posts
                   </a>
 <div class="m-statement__desc">
                     stated on May 14, 2026 in X posts:
                   </div>
 </div>
 </div>
 <div class="m-statement__content">
 <div class="m-statement__body">
 <div class="m-statement__quote-wrap">
 <div class="m-statement__quote">
 <a href="/factchecks/2026/may/15/tweets/byron-donalds-florida-insider-trading/">

                         Video shows U.S. Rep. Byron Donalds saying, “Insider trading should absolutely be allowed for members of Congress.”

                       </a>
 </div>
 </div>
 <div class="m-statement__meter">
 <div class="c-image" style="padding-top: 89.49771689497716%;">
 <img alt="pants-fire" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-pants-fire-th.jpg" width="219"/>
 <picture>
 <img alt="pants-fire" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-pants-fire.jpg" width="219"/>
 </picture>
 </div>
 </div>
 <footer class="m-statement__footer">
                     By Loreben Tuquero • May 15, 2026
                   </footer>
 </div>
 </div>
 </article>
 </li>,
 <li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--false">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/logo-black/4590875651af69b2c789ceab409664dd.jpg" width="83"/>
 <picture>
 <img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/logo-black/72988380e8c8bd188dc360d11552e4a0.jpg" width="166"/>
 </picture>
 </div>
 </div>
 </div>
 <div class="m-statement__meta">
 <a class="m-statement__name" href="/personalities/tweets/" title="X posts">
                      X posts
                   </a>
 <div class="m-statement__desc">
                     stated on May 6, 2026 in an X post:
                   </div>
 </div>
 </div>
 <div class="m-statement__content">
 <div class="m-statement__body">
 <div class="m-statement__quote-wrap">
 <div class="m-statement__quote">
 <a href="/factchecks/2026/may/14/tweets/hantavirus-quarantine-crisis-actor-rosmarin/">

                         An American passenger on the cruise ship involved in the hantavirus outbreak is a "crisis actor."

                       </a>
 </div>
 </div>
 <div class="m-statement__meter">
 <div class="c-image" style="padding-top: 89.49771689497716%;">
 <img alt="false" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-false-th.jpg" width="219"/>
 <picture>
 <img alt="false" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-false.jpg" width="219"/>
 </picture>
 </div>
 </div>
 <footer class="m-statement__footer">
                     By Maria Briceño • May 14, 2026
                   </footer>
 </div>
 </div>
 </article>
 </li>,
 <li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--true">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/Castor/6507dc086f34e06d469d132abf96dd3d.jpg" width="83"/>
 <picture>
 <img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/Castor/d37d7333c8eb3d0cdfbdcdf455779a2d.jpg" width="166"/>
 </picture>
 </div>
 </div>
 </div>
 <div class="m-statement__meta">
 <a class="m-statement__name" href="/personalities/kathy-castor/" title="Kathy Castor">
                     Kathy Castor
                   </a>
 <div class="m-statement__desc">
                     stated on April 29, 2026 in an X post:
                   </div>
 </div>
 </div>
 <div class="m-statement__content">
 <div class="m-statement__body">
 <div class="m-statement__quote-wrap">
 <div class="m-statement__quote">
 <a href="/factchecks/2026/may/14/kathy-castor/kid-care-florida-desantis-health-insurance/">

                         “Florida is the only state in the nation kicking children off their affordable health coverage.”

                       </a>
 </div>
 </div>
 <div class="m-statement__meter">
 <div class="c-image" style="padding-top: 89.49771689497716%;">
 <img alt="true" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-true-th.jpg" width="219"/>
 <picture>
 <img alt="true" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-true.jpg" width="219"/>
 </picture>
 </div>
 </div>
 <footer class="m-statement__footer">
                     By Samantha Putterman • May 14, 2026
                   </footer>
 </div>
 </div>
 </article>
 </li>,
 <li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--mostly-false">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/Screen_Shot_2023-05-04_at_1.14.53_PM/590bc2defa06a0aa0d4d8f871778d5de.jpg" width="83"/>
 <picture>
 <img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/Screen_Shot_2023-05-04_at_1.14.53_PM/941f5c45b00203e04ebaf7010691de5a.jpg" width="166"/>
 </picture>
 </div>
 </div>
 </div>
 <div class="m-statement__meta">
 <a class="m-statement__name" href="/personalities/vivek-ramaswamy/" title="Vivek Ramaswamy">
                     Vivek Ramaswamy
                   </a>
 <div class="m-statement__desc">
                     stated on April 24, 2026 in an ad:
                   </div>
 </div>
 </div>
 <div class="m-statement__content">
 <div class="m-statement__body">
 <div class="m-statement__quote-wrap">
 <div class="m-statement__quote">
 <a href="/factchecks/2026/may/13/vivek-ramaswamy/Amy-Acton-Ohio-2020-covid-primary-senate/">

                         In 2020, “Amy Acton called off Ohio’s election at the last minute.”

                       </a>
 </div>
 </div>
 <div class="m-statement__meter">
 <div class="c-image" style="padding-top: 89.49771689497716%;">
 <img alt="barely-true" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-barely-true-th.jpg" width="219"/>
 <picture>
 <img alt="barely-true" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-barely-true.jpg" width="219"/>
 </picture>
 </div>
 </div>
 <footer class="m-statement__footer">
                     By Amy Sherman • May 13, 2026
                   </footer>
 </div>
 </div>
 </article>
 </li>,
 <li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--false">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/download_11/129886c04abe08501b6b6586038fac7a.jpg" width="83"/>
 <picture>
 <img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/download_11/0367e36ef90ba2d6653597d8486e415c.jpg" width="166"/>
 </picture>
 </div>
 </div>
 </div>
 <div class="m-statement__meta">
 <a class="m-statement__name" href="/personalities/tiktok-posts/" title="TikTok posts">
                      TikTok posts
                   </a>
 <div class="m-statement__desc">
                     stated on May 8, 2026 in una publicación en TikTok:
                   </div>
 </div>
 </div>
 <div class="m-statement__content">
 <div class="m-statement__body">
 <div class="m-statement__quote-wrap">
 <div class="m-statement__quote">
 <a href="/factchecks/2026/may/13/tiktok-posts/hantavirus-infectados-imagenes-crucero/">

                         Imágenes muestran a personas “infectadas con Hantavirus”.

                       </a>
 </div>
 </div>
 <div class="m-statement__meter">
 <div class="c-image" style="padding-top: 89.49771689497716%;">
 <img alt="false" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-false-th.jpg" width="219"/>
 <picture>
 <img alt="false" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-false.jpg" width="219"/>
 </picture>
 </div>
 </div>
 <footer class="m-statement__footer">
                     By Maria Briceño • May 13, 2026
                   </footer>
 </div>
 </div>
 </article>
 </li>,
 <li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--false">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/Christine_Quinn_Thumbnail/06d7995efde9875e085398cc4d3d25b0.jpg" width="83"/>
 <picture>
 <img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/Christine_Quinn_Thumbnail/64da1858f9256082ef4574f94325f346.jpg" width="166"/>
 </picture>
 </div>
 </div>
 </div>
 <div class="m-statement__meta">
 <a class="m-statement__name" href="/personalities/christine-quinn/" title="Christine Quinn">
                     Christine Quinn
                   </a>
 <div class="m-statement__desc">
                     stated on March 5, 2026 in a press release:
                   </div>
 </div>
 </div>
 <div class="m-statement__content">
 <div class="m-statement__body">
 <div class="m-statement__quote-wrap">
 <div class="m-statement__quote">
 <a href="/factchecks/2026/may/11/christine-quinn/new-york-city-homeless-children-yankee-stadium/">

                         “Today, there are more children sleeping in New York City’s homeless shelters than there are seats in Yankee Stadium.”

                       </a>
 </div>
 </div>
 <div class="m-statement__meter">
 <div class="c-image" style="padding-top: 89.49771689497716%;">
 <img alt="false" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-false-th.jpg" width="219"/>
 <picture>
 <img alt="false" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-false.jpg" width="219"/>
 </picture>
 </div>
 </div>
 <footer class="m-statement__footer">
                     By Andrew McGurl • May 11, 2026
                   </footer>
 </div>
 </div>
 </article>
 </li>,
 <li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--true">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/Langworthy_thumbnail/682fdc1f5523c5652c4109b91ca3050a.jpg" width="83"/>
 <picture>
 <img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/Langworthy_thumbnail/0f8a7a4d62a9c924312050cc27b990d8.jpg" width="166"/>
 </picture>
 </div>
 </div>
 </div>
 <div class="m-statement__meta">
 <a class="m-statement__name" href="/personalities/nicholas-langworthy/" title="Nicholas Langworthy">
                     Nicholas Langworthy
                   </a>
 <div class="m-statement__desc">
                     stated on March 31, 2026 in an X post:
                   </div>
 </div>
 </div>
 <div class="m-statement__content">
 <div class="m-statement__body">
 <div class="m-statement__quote-wrap">
 <div class="m-statement__quote">
 <a href="/factchecks/2026/may/11/nicholas-langworthy/tax-refunds-11-percent-reduction-irs/">

                         “The average IRS tax refund is up 11% compared to last year.”

                       </a>
 </div>
 </div>
 <div class="m-statement__meter">
 <div class="c-image" style="padding-top: 89.49771689497716%;">
 <img alt="true" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-true-th.jpg" width="219"/>
 <picture>
 <img alt="true" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-true.jpg" width="219"/>
 </picture>
 </div>
 </div>
 <footer class="m-statement__footer">
                     By Holden Turek • May 11, 2026
                   </footer>
 </div>
 </div>
 </article>
 </li>,
 <li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--false">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/80bd15ec0d50cf908299031c9790109e.jpg" width="83"/>
 <picture>
 <img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c1c32c5a2e0a94447f75d2e6dfe5573d.jpg" width="166"/>
 </picture>
 </div>
 </div>
 </div>
 <div class="m-statement__meta">
 <a class="m-statement__name" href="/personalities/donald-trump/" title="Donald Trump">
                     Donald Trump
                   </a>
 <div class="m-statement__desc">
                     stated on May 7, 2026 in remarks to reporters:
                   </div>
 </div>
 </div>
 <div class="m-statement__content">
 <div class="m-statement__body">
 <div class="m-statement__quote-wrap">
 <div class="m-statement__quote">
 <a href="/factchecks/2026/may/08/donald-trump/gasoline-prices-falling-crude-oil/">

                         Gasoline prices have “come down very substantially today.”

                       </a>
 </div>
 </div>
 <div class="m-statement__meter">
 <div class="c-image" style="padding-top: 89.49771689497716%;">
 <img alt="false" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-false-th.jpg" width="219"/>
 <picture>
 <img alt="false" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-false.jpg" width="219"/>
 </picture>
 </div>
 </div>
 <footer class="m-statement__footer">
                     By Louis Jacobson • May 8, 2026
                   </footer>
 </div>
 </div>
 </article>
 </li>,
 <li class="o-listicle__item">
 <article class="m-statement m-statement--is-medium m-statement--false">
 <div class="m-statement__author">
 <div class="m-statement__avatar">
 <div class="m-statement__image">
 <div class="c-image" style="padding-top: 119.27710843373494%;">
 <img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/Screenshot_2024-07-08_at_5.44.28PM/660719a36f32430483910bdecc8fca21.jpg" width="83"/>
 <picture>

In [3]:
data[0]

<li class="o-listicle__item">
<article class="m-statement m-statement--is-medium m-statement--false">
<div class="m-statement__author">
<div class="m-statement__avatar">
<div class="m-statement__image">
<div class="c-image" style="padding-top: 119.27710843373494%;">
<img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/80bd15ec0d50cf908299031c9790109e.jpg" width="83"/>
<picture>
<img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/new_djt_mugshot/c1c32c5a2e0a94447f75d2e6dfe5573d.jpg" width="166"/>
</picture>
</div>
</div>
</div>
<div class="m-statement__meta">
<a class="m-statement__name" href="/personalities/donald-trump/" title="Donald Trump">
                    Donald Trump
                  </a>
<div class="m-statement__desc">
                    stated on May 18, 2026 in remarks at the White House:
                  </div>
</div>
</div>
<div class="m-statement__content">
<div class="m-statement__body">
<div class="m-statement__quote-wrap">
<div class="m-statement__quote">
<a href="/factchecks/2026/may/20/donald-trump/legal-settlement-fund-weaponization-justice-jan-6/">

                        "There's been numerous other occasions over the years” when the federal government created a reserve similar to a new $1.776 billion anti-weaponization settlement fund.

                      </a>
</div>
</div>
<div class="m-statement__meter">
<div class="c-image" style="padding-top: 89.49771689497716%;">
<img alt="false" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-false-th.jpg" width="219"/>
<picture>
<img alt="false" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-false.jpg" width="219"/>
</picture>
</div>
</div>
<footer class="m-statement__footer">
                    By Louis Jacobson • May 20, 2026
                  </footer>
</div>
</div>
</article>
</li>

In [4]:
len(data)

30

In [5]:
source=[]
print(data[0].find('div',class_="m-statement__meta").find('a').text.strip())

Donald Trump

In [7]:
source=[]
for i in data:
    source.append(i.find('div',class_='m-statement__meta').find('a').text.strip())
print(source)

['Donald Trump', 'Social Media', 'X posts', 'X posts', 'Kathy Castor', 'Vivek Ramaswamy', 'TikTok posts', 'Christine Quinn', 'Nicholas Langworthy', 'Donald Trump', 'Byron Donalds', 'Marcy Kaptur', 'Liz Krueger', 'X posts', 'Donald Trump', 'Sam Sutton', 'Fentrice Driskell', 'Instagram posts', 'Bernie Sanders', 'Tim Scott', 'Pine Tree Results PAC', 'Social Media', 'Donald Trump', 'Ron DeSantis', 'Social Media', 'Jay Collins', 'Robert F. Kennedy Jr.', 'Joe Rogan', 'X posts', 'Chris Wright']

In [20]:
statement=[]
for i in data:
    statement.append(i.find('div',class_='m-statement__quote').text.strip())
print(statement)

['"There\'s been numerous other occasions over the years” when the federal government created a reserve similar to a new $1.776 billion anti-weaponization settlement fund.', '“San Diego mosque shooters identified as trans couple.”', 'Video shows U.S. Rep. Byron Donalds saying, “Insider trading should absolutely be allowed for members of Congress.”', 'An American passenger on the cruise ship involved in the hantavirus outbreak is a "crisis actor."', '“Florida is the only state in the nation kicking children off their affordable health coverage.”', 'In 2020, “Amy Acton called off Ohio’s election at the last minute.”', 'Imágenes muestran a personas “infectadas con Hantavirus”.', '“Today, there are more children sleeping in New York City’s homeless shelters than there are seats in Yankee Stadium.”', '“The average IRS tax refund is up 11% compared to last year.”', 'Gasoline prices have “come down very substantially today.”', 'Congress passed the 1965 Voting Rights Act because “the Democrat party at the time, especially in the South, were racially gerrymandering districts to disenfranchise Black voters.”', 'Republicans “want you to pay $1 Billion for a ballroom.”', 'Proposed data centers in New York state would use “approximately double the energy usage of all households in the state combined.”', '“California only has ‘enough’ oil and gas supply to meet demand for the next six weeks.”', '“Consumer confidence is way up."', 'From January 2025 to January 2026, “hate crimes in New York City increased by 152%”', '“Under federal law, you cannot engage in partisan gerrymandering.”', 'Imagen muestra que “950 inmigrantes derrumbaron el muro fronterizo entre México y Estados Unidos intentando ingresar a Estados Unidos” en abril 2026.', '“As a result of the \'Big Beautiful Bill\' 15 million Americans have been thrown off the healthcare that they need."', '“Secret Service remains unpaid” during the partial government shutdown.', '“Graham Platner blames Maine’s women for getting raped because he says they get f----- up drunk"', 'Video shows “unedited raw security footage” of the shooter at the April 25 White House Correspondents’ Association dinner.', '“We are right now producing more oil than Saudi Arabia and Russia combined.”', 'Since the 2020 census, Florida has "moved from a Democrat majority to a 1.5 million Republican advantage."', '“Tras el atentado a Trump”, en la cena de corresponsales de la Casa Blanca el 25 de abril, “Irán lanza un mensaje fuerte: ‘no le crean nada, miente’”.', 'U.S. Rep. Byron Donalds voted "against three pay raises for military service members, including the largest pay raise for the military in 22 years."', '"There\'s two ways of calculating percentage" decreases. “If you have a $600 drug and you reduce it to $10, that\'s a 600% reduction."', "“With one dose of ibogaine, more than 80% of people are free of (opioid) addiction. With two doses, it's more than 90%.”", "“Newly released FOIA door logs show that former President Joe Biden didn't enter the Oval Office once after the 2024 election.”", 'Solar and wind have not reached “3% of global energy.”']

In [15]:
date=[]
for i in data:
    date.append(i.find('footer',class_='m-statement__footer').text.split(' • ')[-1].strip())
print(date)

['May 20, 2026', 'May 20, 2026', 'May 15, 2026', 'May 14, 2026', 'May 14, 2026', 'May 13, 2026', 'May 13, 2026', 'May 11, 2026', 'May 11, 2026', 'May 8, 2026', 'May 8, 2026', 'May 8, 2026', 'May 7, 2026', 'May 7, 2026', 'May 6, 2026', 'May 5, 2026', 'May 1, 2026', 'April 30, 2026', 'April 30, 2026', 'April 29, 2026', 'April 29, 2026', 'April 29, 2026', 'April 29, 2026', 'April 29, 2026', 'April 28, 2026', 'April 23, 2026', 'April 23, 2026', 'April 22, 2026', 'April 22, 2026', 'April 22, 2026']

In [19]:
links=[]
root='https://www.politifact.com'
for i in data:
    d=i.find('div',class_='m-statement__quote').find('a')['href'].strip()
    links.append(root+d)
print(links)

['https://www.politifact.com/factchecks/2026/may/20/donald-trump/legal-settlement-fund-weaponization-justice-jan-6/', 'https://www.politifact.com/factchecks/2026/may/20/social-media/no-evidence-san-diego-mosque-suspects-trans/', 'https://www.politifact.com/factchecks/2026/may/15/tweets/byron-donalds-florida-insider-trading/', 'https://www.politifact.com/factchecks/2026/may/14/tweets/hantavirus-quarantine-crisis-actor-rosmarin/', 'https://www.politifact.com/factchecks/2026/may/14/kathy-castor/kid-care-florida-desantis-health-insurance/', 'https://www.politifact.com/factchecks/2026/may/13/vivek-ramaswamy/Amy-Acton-Ohio-2020-covid-primary-senate/', 'https://www.politifact.com/factchecks/2026/may/13/tiktok-posts/hantavirus-infectados-imagenes-crucero/', 'https://www.politifact.com/factchecks/2026/may/11/christine-quinn/new-york-city-homeless-children-yankee-stadium/', 'https://www.politifact.com/factchecks/2026/may/11/nicholas-langworthy/tax-refunds-11-percent-reduction-irs/', 'https://www.politifact.com/factchecks/2026/may/08/donald-trump/gasoline-prices-falling-crude-oil/', 'https://www.politifact.com/factchecks/2026/may/08/byron-donalds/florida-voting-rights-act-democrats-gerrymandering/', 'https://www.politifact.com/factchecks/2026/may/08/marcy-kaptur/White-House-Trump-ballroom-East-Wing-1-billion/', 'https://www.politifact.com/factchecks/2026/may/07/liz-krueger/electricity-data-centers-new-york-households/', 'https://www.politifact.com/factchecks/2026/may/07/tweets/california-gasoline-supply-six-weeks/', 'https://www.politifact.com/factchecks/2026/may/06/donald-trump/consumer-confidence-sentiment-spending-second-term/', 'https://www.politifact.com/factchecks/2026/may/05/sam-sutton/hate-crimes-new-york-city-houses-worship/', 'https://www.politifact.com/factchecks/2026/may/01/fentrice-driskell/what-does-federal-law-say-about-partisan-gerrymand/', 'https://www.politifact.com/factchecks/2026/apr/30/instagram-posts/muro-fronterizo-inmigrantes-eeuu-mexico-ia/', 'https://www.politifact.com/factchecks/2026/apr/30/bernie-sanders/one-big-beautiful-bill-ACA-health-care-Medicaid/', 'https://www.politifact.com/factchecks/2026/apr/29/tim-scott/secret-service-assassination-shutdown-paychecks/', 'https://www.politifact.com/factchecks/2026/apr/29/pine-tree-results-pac/Graham-Platner-Collins-Maine-reddit-rape-Senate/', 'https://www.politifact.com/factchecks/2026/apr/29/social-media/correspodents-dinner-shooter-security-footage-AI/', 'https://www.politifact.com/factchecks/2026/apr/29/donald-trump/oil-united-states-russia-saudi-arabia-hormuz-iran/', 'https://www.politifact.com/factchecks/2026/apr/29/ron-desantis/florida-redistricting-republican-democrat-majority/', 'https://www.politifact.com/factchecks/2026/apr/28/social-media/Iran-Trump-tiroteo-cena-casa-blanca/', 'https://www.politifact.com/factchecks/2026/apr/23/jay-collins/byron-donalds-florida-military-pay-votes/', 'https://www.politifact.com/factchecks/2026/apr/23/robert-f-kennedy-jr/percentage-decreases-drug-prices-trump-math/', 'https://www.politifact.com/factchecks/2026/apr/22/joe-rogan/ibogaine-opioid-addiction-psychedelic-withdrawal/', 'https://www.politifact.com/factchecks/2026/apr/22/tweets/Biden-Oval-Office-2024-elections/', 'https://www.politifact.com/factchecks/2026/apr/22/chris-wright/wind-solar-energy-oil-strait-hormuz-iran/']

In [22]:
import pandas as pd

df=pd.DataFrame({'Statements':statement,
                'Source':source,
                'Links':links,
                'Date':date})
df

,Statements,Source,Links,Date
0,"""There's been numerous other occasions over th...","""There's been numerous other occasions over th...",https://www.politifact.com/factchecks/2026/may...,"May 20, 2026"
1,“San Diego mosque shooters identified as trans...,“San Diego mosque shooters identified as trans...,https://www.politifact.com/factchecks/2026/may...,"May 20, 2026"
2,"Video shows U.S. Rep. Byron Donalds saying, “I...","Video shows U.S. Rep. Byron Donalds saying, “I...",https://www.politifact.com/factchecks/2026/may...,"May 15, 2026"
3,An American passenger on the cruise ship invol...,An American passenger on the cruise ship invol...,https://www.politifact.com/factchecks/2026/may...,"May 14, 2026"
4,“Florida is the only state in the nation kicki...,“Florida is the only state in the nation kicki...,https://www.politifact.com/factchecks/2026/may...,"May 14, 2026"
5,"In 2020, “Amy Acton called off Ohio’s election...","In 2020, “Amy Acton called off Ohio’s election...",https://www.politifact.com/factchecks/2026/may...,"May 13, 2026"
6,Imágenes muestran a personas “infectadas con H...,Imágenes muestran a personas “infectadas con H...,https://www.politifact.com/factchecks/2026/may...,"May 13, 2026"
7,"“Today, there are more children sleeping in Ne...","“Today, there are more children sleeping in Ne...",https://www.politifact.com/factchecks/2026/may...,"May 11, 2026"
8,“The average IRS tax refund is up 11% compared...,“The average IRS tax refund is up 11% compared...,https://www.politifact.com/factchecks/2026/may...,"May 11, 2026"
9,Gasoline prices have “come down very substanti...,Gasoline prices have “come down very substanti...,https://www.politifact.com/factchecks/2026/may...,"May 8, 2026"
10,Congress passed the 1965 Voting Rights Act bec...,Congress passed the 1965 Voting Rights Act bec...,https://www.politifact.com/factchecks/2026/may...,"May 8, 2026"
11,Republicans “want you to pay $1 Billion for a ...,Republicans “want you to pay $1 Billion for a ...,https://www.politifact.com/factchecks/2026/may...,"May 8, 2026"
12,Proposed data centers in New York state would ...,Proposed data centers in New York state would ...,https://www.politifact.com/factchecks/2026/may...,"May 7, 2026"
13,“California only has ‘enough’ oil and gas supp...,“California only has ‘enough’ oil and gas supp...,https://www.politifact.com/factchecks/2026/may...,"May 7, 2026"
14,"“Consumer confidence is way up.""","“Consumer confidence is way up.""",https://www.politifact.com/factchecks/2026/may...,"May 6, 2026"
15,"From January 2025 to January 2026, “hate crime...","From January 2025 to January 2026, “hate crime...",https://www.politifact.com/factchecks/2026/may...,"May 5, 2026"
16,"“Under federal law, you cannot engage in parti...","“Under federal law, you cannot engage in parti...",https://www.politifact.com/factchecks/2026/may...,"May 1, 2026"
17,Imagen muestra que “950 inmigrantes derrumbaro...,Imagen muestra que “950 inmigrantes derrumbaro...,https://www.politifact.com/factchecks/2026/apr...,"April 30, 2026"
18,“As a result of the 'Big Beautiful Bill' 15 mi...,“As a result of the 'Big Beautiful Bill' 15 mi...,https://www.politifact.com/factchecks/2026/apr...,"April 30, 2026"
19,“Secret Service remains unpaid” during the par...,“Secret Service remains unpaid” during the par...,https://www.politifact.com/factchecks/2026/apr...,"April 29, 2026"
20,“Graham Platner blames Maine’s women for getti...,“Graham Platner blames Maine’s women for getti...,https://www.politifact.com/factchecks/2026/apr...,"April 29, 2026"
21,Video shows “unedited raw security footage” of...,Video shows “unedited raw security footage” of...,https://www.politifact.com/factchecks/2026/apr...,"April 29, 2026"
22,“We are right now producing more oil than Saud...,“We are right now producing more oil than Saud...,https://www.politifact.com/factchecks/2026/apr...,"April 29, 2026"
23,"Since the 2020 census, Florida has ""moved from...","Since the 2020 census, Florida has ""moved from...",https://www.politifact.com/factchecks/2026/apr...,"April 29, 2026"
24,"“Tras el atentado a Trump”, en la cena de corr...","“Tras el atentado a Trump”, en la cena de corr...",https://www.politifact.com/factchecks/2026/apr...,"April 28, 2026"
25,"U.S. Rep. Byron Donalds voted ""against three p...","U.S. Rep. Byron Donalds voted ""against three p...",https://www.politifact.com/factchecks/2026/apr...,"April 23, 2026"
26,"""There's two ways of calculating percentage"" d...","""There's two ways of calculating percentage"" d...",https://www.politifact.com/factchecks/2026/apr...,"April 23, 2026"
27,"“With one dose of ibogaine, more than 80% of p...","“With one dose of ibogaine, more than 80% of p...",https://www.politifact.com/factchecks/2026/apr...,"April 22, 2026"
28,“Newly released FOIA door logs show that forme...,“Newly released FOIA door logs show that forme...,https://www.politifact.com/factchecks/2026/apr...,"April 22, 2026"
29,Solar and wind have not reached “3% of global ...,Solar and wind have not reached “3% of global ...,https://www.politifact.com/factchecks/2026/apr...,"April 22, 2026"

In [23]:
df.to_excel('politifacts.xlsx')

In [26]:
from bs4 import BeautifulSoup
soup=BeautifulSoup(open('politifact.html','r',encoding='utf-8'))
print(soup.prettify())

<!DOCTYPE html>
<html dir="ltr" lang="en-US">
 <head>
  <meta charset="utf-8"/>
  <meta content="ie=edge" http-equiv="x-ua-compatible"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Fact-checks | PolitiFact
  </title>
  <meta content="PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter." name="description"/>
  <meta content="all" name="robots"/>
  <meta content="PolitiFact" name="publisher"/>
  <meta content="PolitiFact" name="twitter:username"/>
  <meta content="summary" name="twitter:card"/>
  <meta content="PolitiFact" name="twitter:site"/>
  <meta content="" name="twitter:url"/>
  <meta content="" name="twitter:title"/>
  <meta content="PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter." name="twitter:description"/>
  <meta content="vrxxsw8mwnf2pxgnwxvgsn4g93w3vm" name="facebook-domain-verification"/>
  <link href="https://static.politifact.com/images/favicon.ico" rel="shortcut icon" type="image/ico"/>
  <link href="https://static.politifact.com/images/favicon.png" rel="icon" type="image/png"/>
  <link href="https://static.politifact.com/images/apple-touch-icon.png" rel="apple-touch-icon"/>
  <link href="/rss/all/" rel="alternate" title="Latest Fact-checks and Articles" type="application/rss+xml"/>
  <link href="/rss/factchecks/" rel="alternate" title="Latest Fact-checks" type="application/rss+xml"/>
  <script src="https://static.politifact.com/js/sharethefacts-v1.js">
  </script>
  <script src="//d283fm003ll1xs.cloudfront.net/script.js" type="text/javascript">
  </script>
  <script async="" src="//prod.adspsp.com/adb.4026624.min.js" type="text/javascript">
  </script>
  <script async="" src="//securepubads.g.doubleclick.net/tag/js/gpt.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   (function() {
    window.AdBridg = window.AdBridg || {cmd:[]};
    AdBridg.cmd.push({
      action: 'spa_pv_initialize',
      config: {
        targeting: {
          'DOMAIN': 'Poli',
          'PAGE-TYPE': '',

          'Editions': [''],


        }
      }
    });
  })()
  </script>
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-35156640-2">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-35156640-2');
  </script>
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-EDXB0TJGGY">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-EDXB0TJGGY');
  </script>
  <script async="" id="ebx" src="//applets.ebxcdn.com/ebx.js">
  </script>
 </head>
 <body>
  <div id="fb-root">
  </div>
  <script>
   (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
  </script>
  <noscript>
   <img height="1" src="//www.facebook.com/tr?id=292850974235854&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/>
  </noscript>
  <link href="https://static.politifact.com/assets/main-CZkp7TXC.css" rel="stylesheet"/>
  <style>
   .m-notfound{padding-top:2.5rem;padding-bottom:3.5rem}@media print, screen and (min-width: 48em){.m-notfound{padding-top:5rem;padding-bottom:6rem}}.m-notfound__title{margin-bottom:2.5rem;text-align:center}@media print, screen and (min-width: 48em){.m-notfound__content{display:-webkit-box;display:-ms-flexbox;display:flex}}.m-notfound__image{margin-bottom:1.5rem;margin-left:auto;margin-right:auto;max-width:10rem}@media print, screen and (min-width: 48em){.m-notfound__image{-webkit-box-flex:0;-ms-flex:0 0 13.75rem;flex:0 0 13.75rem;max-width:none}}.m-notfound__body{padding-top:.5rem}@media print, screen and (min-width: 48em){.m-notfound__body{padding-left:2rem}}.m-notfound__body p{margin-top:0}
  </style>
  <div class="global-wrapper" id="top">
   <header class="o-header">
    <div class="o-header__inner">
     <div class="o-header__branding">
      <a href="/">
       <span class="m-branding">
        <span class="m-branding__logo">
         <svg class="c-icon">
          <use xlink:href="#svg_logo-plain">
          </use>
         </svg>
        </span>
        <span class="m-branding__subline">
         <span class="m-branding__claim">
          The Poynter Institute
         </span>
        </span>
       </span>
      </a>
     </div>
     <div class="o-header__menu">
      <a class="c-burger" data-menu-toggle="" href="#">
       <span class="c-burger__lines">
       </span>
       <span class="c-burger__value">
        Menu
       </span>
      </a>
     </div>
     <div class="o-header__donate">
      <a class="c-button c-button--small show-for-large" href="/membership/">
       Donate
      </a>
     </div>
    </div>
    <div class="t-menu" data-menu="">
     <div class="t-menu__content">
      <div class="o-menu-list">
       <div class="o-menu-list__inner">
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_1" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_1" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_1" role="tab">
           State Editions
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_1" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/california/">
              California
             </a>
            </li>
            <li>
             <a href="/florida/">
              Florida
             </a>
            </li>
            <li>
             <a href="/iowa/">
              Iowa
             </a>
            </li>
            <li>
             <a href="/michigan/">
              Michigan
             </a>
            </li>
            <li>
             <a href="/new-hampshire/">
              New Hampshire
             </a>
            </li>
            <li>
             <a href="/new-york/">
              New York
             </a>
            </li>
            <li>
             <a href="/north-carolina/">
              North Carolina
             </a>
            </li>
            <li>
             <a href="/pennsylvania/">
              Pennsylvania
             </a>
            </li>
            <li>
             <a href="/texas/">
              Texas
             </a>
            </li>
            <li>
             <a href="/west-virginia/">
              West Virginia
             </a>
            </li>
            <li>
             <a href="/wisconsin/">
              Wisconsin
             </a>
            </li>
            <li>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_2" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_2" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_2" role="tab">
           Issues
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_2" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <strong>
              <a href="/issues/">
               All Issues
              </a>
             </strong>
            </li>
            <li>
             <a href="/facebook-fact-checks/">
              Online hoaxes
             </a>
            </li>
            <li>
             <a href="/coronavirus/">
              Coronavirus
             </a>
            </li>
            <li>
             <a href="/health-check/">
              Health Care
             </a>
            </li>
            <li>
             <a href="/immigration/">
              Immigration
             </a>
            </li>
            <li>
             <a href="https://www.politifact.com/article/2022/jun/09/political-extremism-public-square-resource-journal/">
              Extremism
             </a>
            </li>
            <li>
             <a href="/taxes/">
              Taxes
             </a>
            </li>
            <li>
             <a href="/marijuana/">
              Marijuana
             </a>
            </li>
            <li>
             <a href="/environment/">
              Environment
             </a>
            </li>
            <li>
             <a href="/crime/">
              Crime
             </a>
            </li>
            <li>
             <a href="/guns/">
              Guns
             </a>
            </li>
            <li>
             <a href="/foreign-policy/">
              Foreign Policy
             </a>
            </li>
            <li>
             <a href="/lgbtq/">
              LGBTQ+
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_3" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_3" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_3" role="tab">
           People
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_3" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/personalities/joe-biden/">
              Joe Biden
             </a>
            </li>
            <li>
             <a href="/personalities/kamala-harris/">
              Kamala Harris
             </a>
            </li>
            <li>
             <a href="/personalities/donald-trump/">
              Donald Trump
             </a>
            </li>
            <li>
             <a href="/personalities/mitch-mcconnell/">
              Mitch McConnell
             </a>
            </li>
            <li>
             <a href="/personalities/hakeem-jeffries/">
              Hakeem Jeffries
             </a>
            </li>
            <li>
             <a href="/personalities/ron-desantis/">
              Ron DeSantis
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_4" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_4" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_4" role="tab">
           Media
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_4" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/punditfact/">
              PunditFact
             </a>
            </li>
            <li>
             <a href="/personalities/tucker-carlson/">
              Tucker Carlson
             </a>
            </li>
            <li>
             <a href="/personalities/sean-hannity/">
              Sean Hannity
             </a>
            </li>
            <li>
             <a href="/personalities/rachel-maddow/">
              Rachel Maddow
             </a>
            </li>
            <li>
             <a href="/personalities/blog-posting/">
              Bloggers
             </a>
            </li>
            <li>
             <a href="/videos/">
              PolitiFact Videos
             </a>
            </li>
           </ul>
          </div>
         </div>
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_5" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_5" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_5" role="tab">
           Campaigns
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_5" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/elections/">
              2024 Elections
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_6" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_6" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_6" role="tab">
           Truth-o-Meter
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_6" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/factchecks/list/?ruling=true">
              True
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=mostly-true">
              Mostly True
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=half-true">
              Half True
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=barely-true">
              Mostly False
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=false">
              False
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=pants-fire">
              Pants on Fire
             </a>
            </li>
           </ul>
          </div>
         </div>
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_7" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_7" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_7" role="tab">
           Promises
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_7" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/truth-o-meter/promises/biden-promise-tracker/?ruling=true">
              Biden Promise Tracker
             </a>
            </li>
            <li>
             <a href="/truth-o-meter/promises/trumpometer/?ruling=true">
              Trump-O-Meter
             </a>
            </li>
            <li>
             <a href="/truth-o-meter/promises/obameter/?ruling=true">
              Obameter
             </a>
            </li>
            <li>
             <a href="/truth-o-meter/promises/list/">
              Latest Promises
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_8" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_8" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_8" role="tab">
           About Us
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_8" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/ ">
              Our Process
             </a>
            </li>
            <li>
             <a href="/staff/">
              Our Staff
             </a>
            </li>
            <li>
             <a href="/espanol/">
              En Español
             </a>
            </li>
            <li>
             <a href="/who-pays-for-politifact/">
              Who pays for PolitiFact?
             </a>
            </li>
            <li>
             <a href="/media-kit/">
              Advertise with Us
             </a>
            </li>
            <li>
             <a href="/suggest/statement/">
              Suggest a Fact-check
             </a>
            </li>
            <li>
             <a href="/corrections-and-updates/">
              Corrections and Updates
             </a>
            </li>
            <li>
             <a href="/signup/">
              Newsletters
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
       </div>
      </div>
     </div>
     <div class="o-socializer">
      <div class="o-socializer__item hide-for-large">
       <a class="c-button" href="/membership/">
        Donate
       </a>
      </div>
      <div class="o-socializer__item o-socializer__social">
       <div class="m-follow">
        <h4 class="m-follow__title">
         Follow us
        </h4>
        <div class="m-follow__items">
         <a href="https://twitter.com/Politifact/" title="PolitiFact on Twitter">
          <svg class="c-icon">
           <use xlink:href="#svg_tw">
           </use>
          </svg>
         </a>
         <a href="https://www.facebook.com/politifact/" title="PolitiFact on Facebook">
          <svg class="c-icon">
           <use xlink:href="#svg_fb">
           </use>
          </svg>
         </a>
        </div>
       </div>
      </div>
      <div class="o-socializer__item o-socializer__subscribe">
       <div class="m-subscribe">
        <div class="m-subscribe__title">
         The Facts Newsletter
        </div>
        <label class="c-input">
         <div class="c-input__inner">
          <input class="c-input__field" name="email" placeholder="Enter your email" type="email" value=""/>
         </div>
        </label>
        <a class="c-button c-button--hollow" href="">
         Sign up
        </a>
       </div>
      </div>
     </div>
    </div>
    <div class="o-header__search">
     <div class="m-search">
      <form action="/search/" method="get">
       <input class="m-search__checkbox show-for-sr" data-search="" id="search_form" type="checkbox"/>
       <label class="m-search__toggle" for="search_form" title="Open search form">
        <svg class="c-icon">
         <use xlink:href="#svg_search">
         </use>
        </svg>
       </label>
       <div class="m-search__content">
        <div class="m-search__form">
         <input class="m-search__input" data-search-input="" name="q" placeholder="What are you looking for?" type="search" value=""/>
         <button class="m-search__submit" title="Search" type="submit">
          <svg class="c-icon">
           <use xlink:href="#svg_arrow-thin">
           </use>
          </svg>
         </button>
        </div>
       </div>
      </form>
     </div>
    </div>
   </header>
   <div class="lang-sub-nav m-togglist__list">
    <strong>
     <a href="/">
      English
     </a>
    </strong>
    <a href="/espanol/">
     Español
    </a>
   </div>
   <main class="global-content" role="main">
    <section class="o-disruptor is-active" data-disruptor="">
     <div class="o-disruptor__close" data-disruptor-close="">
      <svg class="c-icon">
       <use xlink:href="#svg_close">
       </use>
      </svg>
     </div>
     <div class="o-disruptor__wrapper">
      <div class="o-disruptor__content">

# For multiple pages

In [27]:
import requests
from bs4 import BeautifulSoup
upperframe=[]
for page in range(1,5):
    url = 'https://www.politifact.com/factchecks/'
    result=requests.get(url)
    content=result.text
    soup=BeautifulSoup(content,'html.parser')

    frame=[]
    data=soup.find_all('li',class_='o-listicle__item')
    for i in data:
         source=i.find('div',class_='m-statement__meta').find('a').text.strip()
         statement=i.find('div',class_='m-statement__quote').text.strip()
         links=i.find('div',class_='m-statement__quote').find('a')['href'].strip()
         date=i.find('footer',class_='m-statement__footer').text.split(' • ')[-1].strip()
         frame.append((statement,source,date,links))
    upperframe.extend(frame)
    
print(len(upperframe))

120

In [38]:
from bs4 import BeautifulSoup
soup=BeautifulSoup(open('top250.html','r',encoding='utf-8'))
print(soup.prettify())

<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
 <head>
  <script type="text/javascript">
   var ue_t0=ue_t0||+new Date();
  </script>
  <script type="text/javascript">
   window.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;
if (window.ue_ihb === 1) {

var ue_csm = window,
    ue_hob = +new Date();
(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);


    var ue_err_chan = 'jserr';
(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.location.href:"");b.logLevel=c;b.attribution=f.attribution||b.attribution;a.erl.push({ex:f,info:b})}}function l(a,b,c,e,g){d.ueLogError({m:a,f:b,l:c,c:""+e,err:g,fromOnError:1,args:arguments},g?{attribution:g.attribution,logLevel:g.logLevel}:void 0);return!1}var k="FATAL",m="ERROR",n="WARN",p="DOWNGRADED",a={ec:0,ecf:0,
pec:0,ts:0,erl:[],ter:[],buffer:[],mxe:50,startTimer:function(){a.ts++;setInterval(function(){d.ue&&a.pec<a.ec&&d.uex("at");a.pec=a.ec},1E4)}};l.skipTrace=1;h.skipTrace=1;h.isStub=1;d.ueLogError=h;d.ue_err=a;e.onerror=l})(ue_csm,window);


var ue_id = '3AQ5G29EBVVKV41WYCWB',
    ue_url,
    ue_navtiming = 1,
    ue_mid = 'A1EVAM02EL8SFB',
    ue_sid = '144-4959287-0258860',
    ue_sn = 'www.imdb.com',
    ue_furl = 'fls-na.amazon.com',
    ue_surl = 'https://unagi-na.amazon.com/1/events/com.amazon.csm.nexusclient.prod',
    ue_int = 0,
    ue_fcsn = 1,
    ue_urt = 3,
    ue_rpl_ns = 'cel-rpl',
    ue_ddq = 1,
    ue_fpf = '//fls-na.amazon.com/1/batch/1/OP/A1EVAM02EL8SFB:144-4959287-0258860:3AQ5G29EBVVKV41WYCWB$uedata=s:',
    ue_sbuimp = 1,
    ue_ibft = 0,
    ue_sswmts = 0,
    ue_jsmtf = 0,
    ue_fnt = 0,
    ue_lpsi = 6000,
    ue_no_counters = 0,

    ue_swi = 1;
var ue_viz=function(){(function(b,e,a){function k(c){if(b.ue.viz.length<p&&!l){var a=c.type;c=c.originalEvent;/^focus./.test(a)&&c&&(c.toElement||c.fromElement||c.relatedTarget)||(a=e[m]||("blur"==a||"focusout"==a?"hidden":"visible"),b.ue.viz.push(a+":"+(+new Date-b.ue.t0)),"visible"==a&&(b.ue.isl&&q("at"),l=1))}}for(var l=0,q=b.uex,f,g,m,n=["","webkit","o","ms","moz"],d=0,p=20,h=0;h<n.length&&!d;h++)if(a=n[h],f=(a?a+"H":"h")+"idden",d="boolean"==typeof e[f])g=a+"visibilitychange",m=(a?a+"V":"v")+
"isibilityState";k({});d&&e.addEventListener(g,k,0);b.ue&&d&&(b.ue.pageViz={event:g,propHid:f})})(ue_csm,ue_csm.document,ue_csm.window)};

(function(d,h,N){function H(a){return a&&a.replace&&a.replace(/^\s+|\s+$/g,"")}function u(a){return"undefined"===typeof a}function B(a,b){for(var c in b)b[v](c)&&(a[c]=b[c])}function I(a){try{var b=N.cookie.match(RegExp("(^| )"+a+"=([^;]+)"));if(b)return b[2].trim()}catch(c){}}function O(k,b,c){var q=(x||{}).type;if("device"!==c||2!==q&&1!==q)k&&(d.ue_id=a.id=a.rid=k,w&&(w=w.replace(/((.*?:){2})(\w+)/,function(a,b){return b+k})),D&&(e("id",D,k),D=0)),b&&(w&&(w=w.replace(/(.*?:)(\w|-)+/,function(a,
c){return c+b})),d.ue_sid=b),c&&a.tag("page-source:"+c),d.ue_fpf=w}function P(){var a={};return function(b){b&&(a[b]=1);b=[];for(var c in a)a[v](c)&&b.push(c);return b}}function y(d,b,c,q){q=q||+new E;var f,m;if(b||u(c)){if(d)for(m in f=b?e("t",b)||e("t",b,{}):a.t,f[d]=q,c)c[v](m)&&e(m,b,c[m]);return q}}function e(d,b,c){var e=b&&b!=a.id?a.sc[b]:a;e||(e=a.sc[b]={});"id"===d&&c&&(Q=1);return e[d]=c||e[d]}function R(d,b,c,e,f){c="on"+c;var m=b[c];"function"===typeof m?d&&(a.h[d]=m):m=function(){};b[c]=
function(a){f?(e(a),m(a)):(m(a),e(a))};b[c]&&(b[c].isUeh=1)}function S(k,b,c,q){function p(b,c){var d=[b],g=0,f={},m,h;c?(d.push("m=1"),f[c]=1):f=a.sc;for(h in f)if(f[v](h)){var q=e("wb",h),p=e("t",h)||{},n=e("t0",h)||a.t0,l;if(c||2==q){q=q?g++:"";d.push("sc"+q+"="+h);for(l in p)u(p[l])||null===p[l]||d.push(l+q+"="+(p[l]-n));d.push("t"+q+"="+p[k]);if(e("ctb",h)||e("wb",h))m=1}}!J&&m&&d.push("ctb=1");return d.join("&")}function m(b,c,g,e,f){if(b){var k=d.ue_err;d.ue_url&&!e&&!f&&b&&0<b.length&&(e=
new Image,a.iel.push(e),e.src=b,a.count&&a.count("postbackImageSize",b.length));w?(f=h.encodeURIComponent)&&b&&(e=new Image,b=""+d.ue_fpf+f(b)+":"+(+new E-d.ue_t0),a.iel.push(e),e.src=b):a.log&&(a.log(b,"uedata",{n:1}),a.ielf.push(b));k&&!k.ts&&k.startTimer();a.b&&(k=a.b,a.b="",m(k,c,g,1))}}function A(b){var c=x?x.type:F,d=2==c||a.isBFonMshop,c=c&&!d,e=a.bfini;Q||(e&&1<e&&(b+="&bfform=1",c||(a.isBFT=e-1)),d&&(b+="&bfnt=1",a.isBFT=a.isBFT||1),a.ssw&&a.isBFT&&(a.isBFonMshop&&(a.isNRBF=0),u(a.isNRBF)&&
(d=a.ssw(a.oid),d.e||u(d.val)||(a.isNRBF=1<d.val?0:1)),u(a.isNRBF)||(b+="&nrbf="+a.isNRBF)),a.isBFT&&!a.isNRBF&&(b+="&bft="+a.isBFT));return b}if(!a.paused&&(b||u(c))){for(var l in c)c[v](l)&&e(l,b,c[l]);a.isBFonMshop||y("pc",b,c);l="ld"===k&&b&&e("wb",b);var s=e("id",b)||a.id;l||s===a.oid||(D=b,ba(s,(e("t",b)||{}).tc||+e("t0",b),+e("t0",b)));var s=e("id",b)||a.id,t=e("id2",b),g=a.url+"?"+k+"&v="+a.v+"&id="+s,J=e("ctb",b)||e("wb",b),z;J&&(g+="&ctb="+J);t&&(g+="&id2="+t);1<d.ueinit&&(g+="&ic="+d.ueinit);
if(!("ld"!=k&&"ul"!=k||b&&b!=s)){if("ld"==k){try{h[K]&&h[K].isUeh&&(h[K]=null)}catch(I){}if(h.chrome)for(t=0;t<L.length;t++)T(G,L[t]);(t=N.ue_backdetect)&&t.ue_back&&t.ue_back.value++;d._uess&&(z=d._uess());a.isl=1}a._bf&&(g+="&bf="+a._bf());d.ue_navtiming&&f&&(e("ctb",s,"1"),a.isBFonMshop||y("tc",F,F,M));!C||a.isBFonMshop||U||(f&&B(a.t,{na_:f.navigationStart,ul_:f.unloadEventStart,_ul:f.unloadEventEnd,rd_:f.redirectStart,_rd:f.redirectEnd,fe_:f.fetchStart,lk_:f.domainLookupStart,_lk:f.domainLookupEnd,
co_:f.connectStart,_co:f.connectEnd,sc_:f.secureConnectionStart,rq_:f.requestStart,rs_:f.responseStart,_rs:f.responseEnd,dl_:f.domLoading,di_:f.domInteractive,de_:f.domContentLoadedEventStart,_de:f.domContentLoadedEventEnd,_dc:f.domComplete,ld_:f.loadEventStart,_ld:f.loadEventEnd,ntd:("function"!==typeof C.now||u(M)?0:new E(M+C.now())-new E)+a.t0}),x&&B(a.t,{ty:x.type+a.t0,rc:x.redirectCount+a.t0}),U=1);a.isBFonMshop||B(a.t,{hob:d.ue_hob,hoe:d.ue_hoe});a.ifr&&(g+="&ifr=1")}y(k,b,c,q);var r,n;l||b&&
b!==s||ca(b);(c=d.ue_mbl)&&c.cnt&&!l&&(g+=c.cnt());l?e("wb",b,2):"ld"==k&&(a.lid=H(s));for(r in a.sc)if(1==e("wb",r))break;if(l){if(a.s)return;g=p(g,null)}else c=p(g,null),c!=g&&(c=A(c),a.b=c),z&&(g+=z),g=p(g,b||a.id);g=A(g);if(a.b||l)for(r in a.sc)2==e("wb",r)&&delete a.sc[r];z=0;a._rt&&(g+="&rt="+a._rt());c=h.csa;if(!l&&c)for(n in r=e("t",b)||{},c=c("PageTiming"),r)r[v](n)&&c("mark",da[n]||n,r[n]);l||(a.s=0,(n=d.ue_err)&&0<n.ec&&n.pec<n.ec&&(n.pec=n.ec,g+="&ec="+n.ec+"&ecf="+n.ecf),z=e("ctb",b),
"ld"!==k||b||a.markers?a.markers&&a.isl&&!l&&b&&B(a.markers,e("t",b)):(a.markers={},B(a.markers,e("t",b))),e("t",b,{}));a.tag&&a.tag().length&&(g+="&csmtags="+a.tag().join("|"),a.tag=P());n=a.viz||[];(r=n.length)&&(g+="&viz="+n.splice(0,r).join("|"));u(d.ue_pty)||(g+="&pty="+d.ue_pty+"&spty="+d.ue_spty+"&pti="+d.ue_pti);a.tabid&&(g+="&tid="+a.tabid);a.aftb&&(g+="&aftb=1");!a._ui||b&&b!=s||(g+=a._ui());a.a=g;m(g,k,z,l,b&&"string"===typeof b&&-1!==b.indexOf("csa:"))}}function ca(a){var b=h.ue_csm_markers||
{},c;for(c in b)b[v](c)&&y(c,a,F,b[c])}function A(a,b,c){c=c||h;if(c[V])c[V](a,b,!1);else if(c[W])c[W]("on"+a,b)}function T(a,b,c){c=c||h;if(c[X])c[X](a,b,!1);else if(c[Y])c[Y]("on"+a,b)}function Z(){function a(){d.onUl()}function b(a){return function(){c[a]||(c[a]=1,S(a))}}var c={},e,f;d.onLd=b("ld");d.onLdEnd=b("ld");d.onUl=b("ul");e={stop:b("os")};h.chrome?(A(G,a),L.push(a)):e[G]=d.onUl;for(f in e)e[v](f)&&R(0,h,f,e[f]);d.ue_viz&&ue_viz();A("load",d.onLd);y("ue")}function ba(e,b,c){var f=d.ue_mbl,
p=h.csa,m=p&&p("SPA"),p=p&&p("PageTiming");f&&f.ajax&&f.ajax(b,c);m&&p&&(m("newPage",{requestId:e,transitionType:"soft"}),p("mark","transitionStart",b));a.tag("ajax-transition")}d.ueinit=(d.ueinit||0)+1;var a=d.ue=d.ue||{};a.t0=h.aPageStart||d.ue_t0;a.id=d.ue_id;a.url=d.ue_url;a.rid=d.ue_id;a.a="";a.b="";a.h={};a.s=1;a.t={};a.sc={};a.iel=[];a.ielf=[];a.viz=[];a.v="0.252726.0";a.paused=!1;var v="hasOwnProperty",G="beforeunload",K="on"+G,V="addEventListener",X="removeEventListener",W="attachEvent",
Y="detachEvent",da={cf:"criticalFeature",af:"aboveTheFold",fn:"functional",fp:"firstPaint",fcp:"firstContentfulPaint",bb:"bodyBegin",be:"bodyEnd",ld:"loaded"},E=h.Date,C=h.performance||h.webkitPerformance,f=(C||{}).timing,x=(C||{}).navigation,M=(f||{}).navigationStart,w=d.ue_fpf,Q=0,U=0,L=[],D=0,F;a.oid=H(a.id);a.lid=H(a.id);a._t0=a.t0;a.tag=P();a.ifr=h.top!==h.self||h.frameElement?1:0;a.markers=null;a.attach=A;a.detach=T;if("000-0000000-8675309"===d.ue_sid){var $=I("cdn-rid"),aa=I("session-id");
$&&aa&&O($,aa,"cdn")}d.uei=Z;d.ueh=R;d.ues=e;d.uet=y;d.uex=S;a.reset=O;a.pause=function(d){a.paused=d};Z()})(ue_csm,ue_csm.window,ue_csm.document);


ue.stub(ue,"log");ue.stub(ue,"onunload");ue.stub(ue,"onflush");
(function(b){var a=b.ue,g=1===b.ue_no_counters;a.cv={};a.cv.scopes={};a.cv.buffer=[];a.count=function(b,f,c){var e={},d=a.cv,h=c&&0===c.c;e.counter=b;e.value=f;e.t=a.d();c&&c.scope&&(d=a.cv.scopes[c.scope]=a.cv.scopes[c.scope]||{},e.scope=c.scope);if(void 0===f)return d[b];d[b]=f;d=0;c&&c.bf&&(d=1);g||(ue_csm.ue_sclog||!a.clog||0!==d||h?a.log&&a.log(e,"csmcount",{c:1,bf:d}):a.clog(e,"csmcount",{bf:d}));a.cv.buffer.push({c:b,v:f})};a.count("baselineCounter2",1);a&&a.event&&(a.event({requestId:b.ue_id||
"rid",server:b.ue_sn||"sn",obfuscatedMarketplaceId:b.ue_mid||"mid"},"csm","csm.CSMBaselineEvent.4"),a.count("nexusBaselineCounter",1,{bf:1}))})(ue_csm);



var ue_hoe = +new Date();
}
window.ueinit = window.ue_ihb;
  </script>
  <!-- k7lm9484vad38cl0y5k0t9znqkgzl4zww198n37crf -->
  <script>
   window.ue && ue.count && ue.count('CSMLibrarySize', 9818)
  </script>
  <meta charset="utf-8"/>
  <script type="text/javascript">
   var IMDbTimer={starttime: new Date().getTime(),pt:'java'};
  </script>
  <script>
   if (typeof uet == 'function') {
      uet("bb", "LoadTitle", {wb: 1});
    }
  </script>
  <script>
   (function(t){ (t.events = t.events || {})["csm_head_pre_title"] = new Date().getTime(); })(IMDbTimer);
  </script>
  <title>
   Top 250 Movies - IMDb
  </title>
  <script>
   (function(t){ (t.events = t.events || {})["csm_head_post_title"] = new Date().getTime(); })(IMDbTimer);
  </script>
  <script>
   if (typeof uet == 'function') {
      uet("be", "LoadTitle", {wb: 1});
    }
  </script>
  <script>
   if (typeof uex == 'function') {
      uex("ld", "LoadTitle", {wb: 1});
    }
  </script>
  <link href="https://www.imdb.com/chart/top/" rel="canonical"/>
  <meta content="http://www.imdb.com/chart/top/" property="og:url"/>
  <script>
   if (typeof uet == 'function') {
      uet("bb", "LoadIcons", {wb: 1});
    }
  </script>
  <script>
   (function(t){ (t.events = t.events || {})["csm_head_pre_icon"] = new Date().getTime(); })(IMDbTimer);
  </script>
  <link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_desktop_32x32._CB1582158068_.png" rel="icon" sizes="32x32"/>
  <link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_iPad_retina_167x167._CB1582158068_.png" rel="icon" sizes="167x167"/>
  <link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_iPhone_retina_180x180._CB1582158069_.png" rel="icon" sizes="180x180"/>
  <link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-mobile._CB479963088_.png" rel="apple-touch-icon"/>
  <link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-mobile-76x76._CB479962152_.png" rel="apple-touch-icon" sizes="76x76"/>
  <link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-mobile-120x120._CB479963088_.png" rel="apple-touch-icon" sizes="120x120"/>
  <link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-web-152x152._CB479963088_.png" rel="apple-touch-icon" sizes="152x152"/>
  <link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/android-mobile-196x196._CB479962153_.png" rel="shortcut icon" sizes="196x196"/>
  <meta content="#000000" name="theme-color"/>
  <link href="https://m.media-amazon.com/images/S/sash/MzfIBMq9GBucYqW.xml" rel="search" title="IMDb" type="application/opensearchdescription+xml"/>
  <script>
   (function(t){ (t.events = t.events || {})["csm_head_post_icon"] = new Date().getTime(); })(IMDbTimer);
  </script>
  <script>
   if (typeof uet == 'function') {
      uet("be", "LoadIcons", {wb: 1});
    }
  </script>
  <script>
   if (typeof uex == 'function') {
      uex("ld", "LoadIcons", {wb: 1});
    }
  </script>
  <title>
   Top 250 Movies
  </title>
  <meta content="Check out the top 250 movies as rated by IMDb users" name="description"/>
  <meta content="index,follow" name="robots"/>
  <meta content="Check out the top 250 movies as rated by IMDb users" itemprop="description"/>
  <meta content="https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SY1000_CR0,0,666,1000_AL_.jpg" itemprop="image"/>
  <meta content="Top 250 Movies" itemprop="name"/>
  <meta content="chart" property="pageType"/>
  <meta content="top250movie" property="subpageType"/>
  <meta content="3AQ5G29EBVVKV41WYCWB" name="requestId"/>
  <meta content="115109575169727" property="fb:app_id"/>
  <meta content="website" property="og:type"/>
  <meta content="Check out the top 250 movies as rated by IMDb users" property="og:description"/>
  <meta content="https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SY1000_CR0,0,666,1000_AL_.jpg" property="og:image"/>
  <meta content="IMDb" property="og:site_name"/>
  <meta content="Top 250 Movies" property="og:title"/>
  <meta content="Check out the top 250 movies as rated by IMDb users" name="twitter:description"/>
  <meta content="https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SY1000_CR0,0,666,1000_AL_.jpg" name="twitter:image"/>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="@IMDb" name="twitter:site"/>
  <meta content="Top 250 Movies" name="twitter:title"/>
  <script>
   (function (win) {
            win.PLAID_LOAD_FONTS_FIRED = true;

            if (typeof win.FontFace !== "undefined"
                && typeof win.Promise !== "undefined") {
                if (win.ue) {
                    win.uet("bb", "LoadRoboto", { wb: 1 });
                }
                var allowableLoadTime = 1000;
                var startTimeInt = +new Date();
                var roboto = new FontFace('Roboto',
                    'url(https://m.media-amazon.com/images/G/01/IMDb/cm9ib3Rv.woff2)',
                    { style:'normal', weight: 400 });
                var robotoMedium = new FontFace('Roboto',
                    'url(https://m.media-amazon.com/images/G/01/IMDb/cm9ib3RvTWVk.woff2)',
                    { style:'normal', weight: 500 });
                var robotoBold = new FontFace('Roboto',
                    'url(https://m.media-amazon.com/images/G/01/IMDb/cm9ib3RvQm9sZA.woff2)',
                    { style:'normal', weight: 600 });
                var robotoLoaded = roboto.load();
                var robotoMediumLoaded = robotoMedium.load();
                var robotoBoldLoaded = robotoBold.load();

                win.Promise.all([robotoLoaded, robotoMediumLoaded, robotoBoldLoaded]).then(function() {
                    var loadTimeInt = +new Date();
                    var robotoLoadedCount = 0;
                    if ((loadTimeInt - startTimeInt) <= allowableLoadTime) {
                        win.document.fonts.add(roboto);
                        win.document.fonts.add(robotoMedium);
                        win.document.fonts.add(robotoBold);
                        robotoLoadedCount++;
                    }
                    if (win.ue) {
                        win.ue.count("roboto-loaded", robotoLoadedCount);
                        win.uet("be", "LoadRoboto", { wb: 1 });
                        win.uex("ld", "LoadRoboto", { wb: 1 });
                    }
                }).catch(function() {
                    if (win.ue) {
                        win.ue.count("roboto-loaded", 0);
                    }
                });
            } else {
                if (win.ue) {
                    win.ue.count("roboto-load-not-attempted", 1);
                }
            }
        })(window);
  </script>
  <script>
   if (typeof uet == 'function') {
      uet("bb", "LoadCSS", {wb: 1});
    }
  </script>
  <script>
   (function(t){ (t.events = t.events || {})["csm_head_pre_css"] = new Date().getTime(); })(IMDbTimer);
  </script>
  <!-- h=ics-c52xl-14-1e-2261c536.us-east-1 -->
  <link href="https://m.media-amazon.com/images/S/sash/3C8rXmQe1JaR36i.css" rel="stylesheet" type="text/css"/>
  <link href="https://m.media-amazon.com/images/S/sash/i-Y65BmJrKWIfbK.css" rel="stylesheet" type="text/css"/>
  <link href="https://m.media-amazon.com/images/S/sash/slv5VSx7C6CBx8a.css" rel="stylesheet" type="text/css"/>
  <link href="https://m.media-amazon.com/images/S/sash/mrwUCCyp3V14GU0.css" rel="stylesheet" type="text/css"/>
  <link href="https://m.media-amazon.com/images/S/sash/4w4OQGgDeMIrb8f.css" rel="stylesheet" type="text/css"/>
  <noscript>
   <link href="https://m.media-amazon.com/images/S/sash/CCc6Ja$8QUPPKkY.css" rel="stylesheet" type="text/css"/>
  </noscript>
  <script>
   (function(t){ (t.events = t.events || {})["csm_head_post_css"] = new Date().getTime(); })(IMDbTimer);
  </script>
  <script>
   if (typeof uet == 'function') {
      uet("be", "LoadCSS", {wb: 1});
    }
  </script>
  <script>
   if (typeof uex == 'function') {
      uex("ld", "LoadCSS", {wb: 1});
    }
  </script>
  <script>
   if (typeof uet == 'function') {
      uet("bb", "LoadJS", {wb: 1});
    }
  </script>
  <script>
   if (typeof uet == 'function') {
      uet("bb", "LoadHeaderJS", {wb: 1});
    }
  </script>
  <script>
   (function(t){ (t.events = t.events || {})["csm_head_pre_ads"] = new Date().getTime(); })(IMDbTimer);
  </script>
  <script>
   window.ads_js_start = new Date().getTime();
var imdbads = imdbads || {}; imdbads.cmd = imdbads.cmd || [];
  </script>
  <!-- begin SRA -->
  <script>

In [39]:
movie=soup.find_all('td',class_='titleColumn')
len(movie)

250

In [40]:
title=[]
for i in movie:
    title.append(i.find('a').text.strip())
print(title)

['The Shawshank Redemption', 'The Godfather', 'The Dark Knight', 'The Godfather Part II', '12 Angry Men', "Schindler's List", 'The Lord of the Rings: The Return of the King', 'Pulp Fiction', 'The Lord of the Rings: The Fellowship of the Ring', 'The Good, the Bad and the Ugly', 'Spider-Man: Across the Spider-Verse', 'Forrest Gump', 'Fight Club', 'The Lord of the Rings: The Two Towers', 'Inception', 'Star Wars: Episode V - The Empire Strikes Back', 'The Matrix', 'Goodfellas', "One Flew Over the Cuckoo's Nest", 'Se7en', "It's a Wonderful Life", 'Seven Samurai', 'The Silence of the Lambs', 'Saving Private Ryan', 'City of God', 'Interstellar', 'Life Is Beautiful', 'The Green Mile', 'Star Wars: Episode IV - A New Hope', 'Terminator 2: Judgment Day', 'Back to the Future', 'Spirited Away', 'The Pianist', 'Psycho', 'Parasite', 'Léon: The Professional', 'The Lion King', 'Gladiator', 'American History X', 'The Departed', 'Whiplash', 'The Prestige', 'The Usual Suspects', 'Casablanca', 'Grave of the Fireflies', 'Harakiri', 'The Intouchables', 'Modern Times', 'Once Upon a Time in the West', 'Cinema Paradiso', 'Rear Window', 'Alien', 'City Lights', 'Apocalypse Now', 'Memento', 'Django Unchained', 'Indiana Jones and the Raiders of the Lost Ark', 'WALL·E', 'The Lives of Others', 'Sunset Blvd.', 'Paths of Glory', 'Avengers: Infinity War', 'The Shining', 'The Great Dictator', 'Witness for the Prosecution', 'Spider-Man: Into the Spider-Verse', 'Aliens', 'American Beauty', 'The Dark Knight Rises', 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'Inglourious Basterds', 'Oldboy', 'Coco', 'Amadeus', 'Toy Story', 'Braveheart', 'Das Boot', 'Joker', 'Avengers: Endgame', 'Princess Mononoke', 'Good Will Hunting', 'Once Upon a Time in America', 'Your Name.', '3 Idiots', "Singin' in the Rain", 'High and Low', 'Requiem for a Dream', 'Capernaum', 'Toy Story 3', 'Star Wars: Episode VI - Return of the Jedi', 'Come and See', 'Eternal Sunshine of the Spotless Mind', '2001: A Space Odyssey', 'The Hunt', 'Reservoir Dogs', 'Lawrence of Arabia', 'Citizen Kane', 'M', 'Ikiru', 'North by Northwest', 'The Apartment', 'Vertigo', 'Amélie', 'Double Indemnity', 'A Clockwork Orange', 'Full Metal Jacket', 'Hamilton', 'Scarface', 'Incendies', 'Heat', 'Up', 'To Kill a Mockingbird', 'The Sting', 'A Separation', 'Metropolis', 'L.A. Confidential', 'Die Hard', 'Indiana Jones and the Last Crusade', 'Snatch', 'Taxi Driver', 'Bicycle Thieves', 'Like Stars on Earth', '1917', 'Dangal', 'Downfall', 'Top Gun: Maverick', 'For a Few Dollars More', 'Batman Begins', 'The Kid', 'Some Like It Hot', 'The Father', 'The Wolf of Wall Street', 'All About Eve', 'Green Book', 'Judgment at Nuremberg', 'Ran', 'The Truman Show', 'Casino', 'There Will Be Blood', "Pan's Labyrinth", 'Unforgiven', 'Shutter Island', 'The Sixth Sense', 'Jurassic Park', 'A Beautiful Mind', 'The Treasure of the Sierra Madre', 'Yojimbo', 'Monty Python and the Holy Grail', 'No Country for Old Men', 'Kill Bill: Vol. 1', 'The Great Escape', 'Rashomon', 'The Thing', 'Finding Nemo', 'Spider-Man: No Way Home', 'The Elephant Man', 'Chinatown', 'Raging Bull', 'V for Vendetta', 'Gone with the Wind', 'Dial M for Murder', 'Inside Out', 'Lock, Stock and Two Smoking Barrels', "Howl's Moving Castle", 'The Secret in Their Eyes', 'Guardians of the Galaxy Vol. 3', 'Three Billboards Outside Ebbing, Missouri', 'Prisoners', 'Trainspotting', 'The Bridge on the River Kwai', 'Fargo', 'Warrior', 'Gran Torino', 'Catch Me If You Can', 'My Neighbor Totoro', 'Million Dollar Baby', 'Children of Heaven', 'The Gold Rush', 'Blade Runner', 'Klaus', 'Harry Potter and the Deathly Hallows: Part 2', '12 Years a Slave', 'Before Sunrise', 'The Grand Budapest Hotel', 'Ben-Hur', 'On the Waterfront', 'Gone Girl', 'The General', 'Barry Lyndon', 'Wild Strawberries', 'In the Name of the Father', 'The Deer Hunter', 'Hacksaw Ridge', 'The Third Man', 'The Wages of Fear', 'Memories of Murder', 'Sherlock Jr.', 'Wild Tales', 'Mr. Smith Goes to Washington', 'Mad Max: Fury Road', 'Mary and Max', 'Dead Poets Society', 'How to Train Your Dragon', 'Monsters, Inc.', 'The Seventh Seal', 'Jaws', 'Room', 'The Big Lebowski', 'Tokyo Story', 'Ford v Ferrari', 'The Passion of Joan of Arc', 'Hotel Rwanda', 'Rocky', 'Ratatouille', 'Platoon', 'Spotlight', 'Logan', 'The Terminator', 'Jai Bhim', 'Rush', 'Stand by Me', 'Before Sunset', 'Network', 'Into the Wild', 'The Wizard of Oz', 'The Best Years of Our Lives', 'The Exorcist', 'La haine', 'The Incredibles', 'To Be or Not to Be', 'Groundhog Day', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Battle of Algiers', 'The Grapes of Wrath', 'My Father and My Son', "Hachi: A Dog's Tale", 'Pather Panchali', 'The Handmaiden', 'Amores Perros', 'Rebecca', 'Cool Hand Luke', 'The Sound of Music', 'It Happened One Night', 'The 400 Blows', 'Persona', 'The Help', 'Life of Brian', 'The Iron Giant', 'Aladdin', 'Dances with Wolves']

In [42]:
year=[]
for i in movie:
    year.append(i.find('span',class_='secondaryInfo').text[1:-1].strip())
print(year)

['1994', '1972', '2008', '1974', '1957', '1993', '2003', '1994', '2001', '1966', '2023', '1994', '1999', '2002', '2010', '1980', '1999', '1990', '1975', '1995', '1946', '1954', '1991', '1998', '2002', '2014', '1997', '1999', '1977', '1991', '1985', '2001', '2002', '1960', '2019', '1994', '1994', '2000', '1998', '2006', '2014', '2006', '1995', '1942', '1988', '1962', '2011', '1936', '1968', '1988', '1954', '1979', '1931', '1979', '2000', '2012', '1981', '2008', '2006', '1950', '1957', '2018', '1980', '1940', '1957', '2018', '1986', '1999', '2012', '1964', '2009', '2003', '2017', '1984', '1995', '1995', '1981', '2019', '2019', '1997', '1997', '1984', '2016', '2009', '1952', '1963', '2000', '2018', '2010', '1983', '1985', '2004', '1968', '2012', '1992', '1962', '1941', '1931', '1952', '1959', '1960', '1958', '2001', '1944', '1971', '1987', '2020', '1983', '2010', '1995', '2009', '1962', '1973', '2011', '1927', '1997', '1988', '1989', '2000', '1976', '1948', '2007', '2019', '2016', '2004', '2022', '1965', '2005', '1921', '1959', '2020', '2013', '1950', '2018', '1961', '1985', '1998', '1995', '2007', '2006', '1992', '2010', '1999', '1993', '2001', '1948', '1961', '1975', '2007', '2003', '1963', '1950', '1982', '2003', '2021', '1980', '1974', '1980', '2005', '1939', '1954', '2015', '1998', '2004', '2009', '2023', '2017', '2013', '1996', '1957', '1996', '2011', '2008', '2002', '1988', '2004', '1997', '1925', '1982', '2019', '2011', '2013', '1995', '2014', '1959', '1954', '2014', '1926', '1975', '1957', '1993', '1978', '2016', '1949', '1953', '2003', '1924', '2014', '1939', '2015', '2009', '1989', '2010', '2001', '1957', '1975', '2015', '1998', '1953', '2019', '1928', '2004', '1976', '2007', '1986', '2015', '2017', '1984', '2021', '2013', '1986', '2004', '1976', '2007', '1939', '1946', '1973', '1995', '2004', '1942', '1993', '2003', '1966', '1940', '2005', '2009', '1955', '2016', '2000', '1940', '1967', '1965', '1934', '1959', '1966', '2011', '1979', '1999', '1992', '1990']

In [47]:
rating=[]
for i in soup.find_all('td',class_='ratingColumn imdbRating'):
    rating.append(i.text.strip())
print(rating)

['9.2', '9.2', '9.0', '9.0', '9.0', '8.9', '8.9', '8.8', '8.8', '8.8', '8.8', '8.8', '8.7', '8.7', '8.7', '8.7', '8.7', '8.7', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.5', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.4', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.3', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.2', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.1', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0']

In [48]:
df=pd.DataFrame({'Title':title,'Year':year,'rating':rating})
df

                        Title  Year rating
0    The Shawshank Redemption  1994    9.2
1               The Godfather  1972    9.2
2             The Dark Knight  2008    9.0
3       The Godfather Part II  1974    9.0
4                12 Angry Men  1957    9.0
..                        ...   ...    ...
245                  The Help  2011    8.0
246             Life of Brian  1979    8.0
247            The Iron Giant  1999    8.0
248                   Aladdin  1992    8.0
249        Dances with Wolves  1990    8.0

[250 rows x 3 columns]